#import "polylux/polylux.typ": *
#import "polylux/l-m.dev.typ": *

#set raw(tab-size: 4)
#show: metropolis-theme.with()
#set par(justify: true)

#let l-m-todo(body) = [#text(fill: l-m-meta-colour)[\/\/ ]#text(fill: l-m-accent-colour)[TODO: ] #text(fill: l-m-meta-colour, body)]
#let l-m-tldr(body) = [#text(fill: l-m-meta-colour)[\/\/ ]#text(fill: l-m-accent-colour)[tldr: ] #text(fill: l-m-meta-colour, body)]
#let span-sep(left, right) = box[#left #box(width: 1fr, repeat[#text(fill: l-m-meta-colour)[-]]) #right]

#let l-m-meta(body) = text(fill: l-m-meta-colour, body)

#let uncoverb(b, body) = uncover((beginning: b), body)

#let gc = block.with(
  width: 100%,
  height: 100%,
)

#let gh = block.with(
  width: 100%,
)

#title-slide({
  l-m-title("Zero to RandomX.js")
  linebreak()
  l-m-title("")
  l-m-hr()
  set text(size: 0.8em)
  text(fill: l-m-meta-colour, "Tuesday, October 3rd | Lecture Theatre 123 | 6 PM - 8 PM")
})

#slide(title: "About me")[
  - Liam, l-m, #underline[l-m.dev], #underline[l-m\@l-m.dev]
]

#focus-slide()[
  Let Me Paint A Picture. TODO change this
]

/*
*/
#slide(title: "What is Monero?")[
  - Introduce
]


/* TODO: Required knowledge
    - Hashes
*/
#new-section-slide[(1.POW) Proof-of-Work Consensus]

#new-section-slide[(2.RX) RandomX]

/*
- (3) By then, ASICs for cryptonight have already been created, so the switch was needed.
*/
#slide(title: [(2.RX) RandomX])[

  RandomX is a proof-of-work algorithm that is optimized for general-purpose CPUs. It has stood the test of time as an *ASIC resistant* hash function.

  #uncover((2, 3))[
    On November 30th, 2019, Monero switched from its old POW algorithm, _cryptonight_, to RandomX. #uncover(3)[
      #text(fill: rgb("#f26822"))[Which had already been broken.]
    ]
  ]

  #uncover(3)[
    #l-m-hr()
    #quote[
      RandomX uses random code execution (hence the name) together with several memory-hard techniques to minimize the efficiency advantage of specialized hardware.
    ]

    #l-m-meta[(Reminder: the goal is to make the CPU the perfect ASIC.)]

    #v(1em)

    https://github.com/tevador/RandomX
  ]
]

/*
- This is RandomX on a high level. This is supposed to resemble a CPU and this is supposed to be 2 GiB
  of fixed read only memory for it to sample from.

  The hash function accepts two input values:

  - String K with a size of 0-60 bytes (key)
  - String H of arbitrary length (the value to be hashed)

  and outputs a 256-bit result R.

  Intended use states that you fix the key, and you build the dataset from that which can take multiple
  seconds. Once the key is fixed you can use it like a regular hash function.

  You can think of these as two separate units, black boxes. The only thing the VM will
  ask the dataset is to read its items, which are 64 bytes in length each.

  As you can see in the corner there, the VM has a 2 KiB scratchpad which is basically its working
  memory, which is divvied up into L1, L2, L3. The point of the VM is to blast the scratchpad with entropy
  and then hash it along with it's registers. That's the final result.

  So what I'm going to do is look at these in separate pieces.
*/
#slide-background(
  background: image("randomx architecture simplified.png", fit: "cover", width: 120%, height: 120%),
)[]

/*
- (3) A hint here is that you actually don't need to lug around 2 GiB dataset, you can generate it on
      the fly from the dataset cache, which is only 256 MiBs.

      If you want to mine fast, you generate the entire 2 GiBs up front, but, if you just want to mine
      on a memory budget or verify someones hash, you only need the 256 MiB "cache" as you can run
      the 8 hash functions on demand. This is called light-verification, or light-mode.

      The most important thing to take from this slide is that the RandomX VM will ask for items,
      and those items are generated by executing 8 hash functions derived from the key.
      So these hash functions are generated just in time, they're just programs.
*/
#slide-background(
  background: image("randomx architecture dataset.png", fit: "cover", width: 110%, height: 110%),
  inset: 1.2em
)[
  #set align(top)
  #set text(size: 0.8em)

  #grid(columns: (10fr, 9fr), gutter: 0em, gc[], gc[
    #uncover((2, 3))[
      Pre-initialisation.

      - The key $K$ is passed to the SSH generator, which generates 8 hash functions.
      - $K$ is also used to fill 256 MiBs of static memory.
    ]

    #uncover(3)[
      #l-m-hr()
      Dataset-initialisation.

      - Each 64-byte Dataset item is generated by executing each of those 8 functions, and XORing data from the cache.
      - Cache $==>$ Dataset.
    ]
  ])
]

/*
*/
#slide(title: [(2.RX) Superscalar?], inset: 1em)[
  #set align(top)

  CPUs are _very_ good at executing arbitrary code.

  #grid(columns: (5fr, 4fr), gutter: 1em, gh[
    #set align(top)
    #v(1em)
    
    ```yasm
        add rax, rbx      ; (1) a = a + b
        imul rcx, rdx     ; (2) c = c * d
        sub rbx, 5        ; (3) b = b - 5
    ```
    #uncover((2, 3, 4, 5, 6, 7))[
      ```yasm
          ; (1) (2) (3) executed all at once (superscalar)
      ```
    ]
    ```yasm
        and rax, rcx      ; (4) a = a & c
        cmp rbx, 0        ; (5) test b with 0
    ```
    #uncover((3, 4, 5, 6, 7))[
    ```yasm
        ; (3) -> (5). (OoO-execution)
    ```
    ]
    
  ], gh[
    #v(1em)

    #uncover((4, 5, 6, 7))[
      ```yasm
        ; OoO, bundle (3) with (5).
        ; superscalar, execute both bundles at once
        add rax, rbx      ; (1) a = a + b
        imul rcx, rdx     ; (2) c = c * d
        and rax, rcx      ; (4) a = a & c

        sub rbx, 5        ; (3) b = b - 5
        cmp rbx, 0        ; (5) test b with 0
      ```
    ]
  ])
  #uncover((4, 5, 6, 7))[
    #l-m-hr()
  ]
  #grid(columns: (5fr, 4fr), gutter: 1em, gc[
    ```yasm

        jg l0             ; (6) if (b > 0) goto l0;
        mov rdx, rax      ; (7) d = a
    l0:
        xor rax, rax      ; (8) a = 0
    ```
    #uncover((5, 6, 7))[
      ```yasm
          ; (BP and speculative execution)
          ; at (6), optimistically guess that (b > 0) and
          ; skip straight to executing (8), aborting if wrong
      ```
    ]
  ], gc[
    #uncover((6, 7))[
      ```yasm

          add rax, rbx   ; writes to rax
          ;                ... code that uses rax
          mov rax, 5     ; also writes to rax
          ;                ... code that uses rax
      ```
    ]
    #uncover(7)[
      ```yasm


          ; RR will rename rax -> r0, execute the
          ; mov bundle with the add bundle.
      ```
    ]    
  ])
]

/*
- (1) If you didn't get all that, that's okay. The important things to take away is that CPU's are:
- (6) ... this to drive away ASICs. I'll give an example of how SuperscalarHash function is generated.
*/
#slide(title: [(2.RX) Superscalar?], inset: 2em)[
  CPUs are:

  #uncover((2, 3, 4, 5, 6))[
    1. Superscalar #l-m-meta[(execute multiple instructions at once)]
  ]
  #uncover((3, 4, 5, 6))[
    2. OoO-execution #l-m-meta[(reorder instructions)]
  ]
  #uncover((4, 5, 6))[
    3. Speculative execution #l-m-meta[(optimistically guess branches)]
  ]
  #uncover((5, 6))[
    4. Register renaming #l-m-meta[(more registers than it seems)]
  ]

  #uncover(6)[
    #v(1em)
    All of these increase Instruction-Level-Parallelism (ILP).
    
    #l-m-hr()

    Generated code in RandomX needs to take advantage of this!
  ]
]

/*
- CPU ..., generating code to saturate its ALU.

- NOTE: These are integer instructions only! The RandomX VM also uses floating point.
*/
#slide(title: [(2.RX) Maximising ILP])[
  #quote[SuperscalarHash is a custom diffusion function that was designed to burn as much power as possible using only the CPU's integer ALUs.]

  #v(1em)
  
  - RandomX wants to increase ILP,
  - so superscalarhash-functions are generated by simulating a reference superscalar CPU #l-m-meta[(Intel Ivy Bridge µarch)].

  #l-m-hr()

  - It assumes a CPU with 3 parallel integer execution ports (P0, P1, P5).

    #l-m-meta[(Multiplication can only run on P5, etc.)]
    
  - Schedules an instruction on every available port, for every cycle.
]
/* TODO: add in uncover */


/*
- (1) After each execution of a SuperscalarHash, the next cache index is set to the register that has the
      longest dependency chain in that superscalarhash to minimise how much a would be ASIC could
      parallelise the execution of the hash and force execution to be overall a straight line where
      CPUs excel.

- (2) And that's it! This is the entire Dataset side of RandomX. If you want to do light-mining or
      verification, the RandomX VM will call this `getItem` every time it needs to access the dataset.

      If you're not doing light-verfication and want to mine, just generate all of the 2 GiB dataset
      items ahead of time, which will take a couple seconds.

- (3) If you think that we could stop here and make this our RandomX, as it's pretty good already,
      know that this minus the cache is a part of what Tor uses for it's client puzzles. All the
      techniques for burning through a CPUs ILP is replicated in Equi-X, among others.
*/
#slide(title: [(2.RX) SuperscalarHash], inset: 1em)[
  #set align(top)

  #grid(columns: (5fr, 4fr), gutter: 1em, gc[
    = *Algorithm.*

    #v(1em)

    ```
    cacheIndex = item number
    r0 = (item number + 1) * 6364136223846793005
    r1 = r0 ^ 9298411001130361340
    
    i = 0
    do {
        block = cache[cacheIndex % nr. 64 bytes in cache]
        SuperscalarHash[i](r0, r1, r2, r3, r4, r5, r6, r7)
        r0..7 ^= block[0..7]
        cacheIndex = r[longest dependency chain]
        i = i + 1
    } while(i < 8)

    item data = (r0|r1|r2|r3|r4|r5|r6|r7)
    ```

    #uncover((2, 3))[
      #l-m-hr()    
      #l-m-meta[(That's really all there is to the Dataset.)]
    ]
    #uncover(3)[

      https://github.com/tevador/equix #l-m-meta[(Tor)]
    ]
  ], gc[
      #set text(size: 0.8em)
      ```yasm
      getItem:
        ; r0 = (itemNumber + 1) * 6364136223846793005
        mov r8, rdi
        add r8, 1
        mov rax, 6364136223846793005
        imul r8, rax

        ; r1 = r0 ^ 9298411001130361340 ... and so on for r2-r7
        mov r9, -9148333072579190276   ;
        xor r9, r8                     ; r9 (r1) = r0 ^ constant
        mov r10, -6381431487974942650  ;
        xor r10, r8                    ; r10 (r2) = r0 ^ constant
        ; ...
        ; ...
        ;
        ; execute SuperscalarHash[i](r0, ..., r7)

        ; each invocation is unrolled in the generated code,
        ; no loop here.
        imul r12, r15             ; IMUL_R r4, r7
        imul r13, r14             ; IMUL_R r5, r6
        imul r10, r11             ; IMUL_R r2, r3
        lea r14, [r14 + r11*2]    ; IADD_RS r6, r3 (shift 1)
        xor r15, r9               ; IXOR_R r7, r1
        mov rax, -1727223807      ;
        xor r8, rax               ; IXOR_C r0, imm32
        sub r15, r14              ; ISUB_R r7, r6 (going down ↓)
        ; ...................
      ```
  ])
]

/*
- So, to recap:
*/
#slide-background(
  background: image("randomx architecture dataset.png", fit: "cover", width: 110%, height: 110%),
  inset: 1.2em
)[
  #set align(top)
  #set text(size: 0.8em)

  #grid(columns: (10fr, 9fr), gutter: 0em, gc[], gc[
    Pre-initialisation.

    - The key $K$ is passed to the SSH generator, which generates 8 hash functions.
    - $K$ is also used to fill 256 MiBs of static memory.

    #l-m-hr()
    Dataset-initialisation.

    - Each 64-byte Dataset item is generated by executing each of those 8 functions, and XORing data from the cache.
    - Cache $==>$ Dataset.
  ])
]
/*
- An important thing to remmeber here is that we can generate the 2 GiBs of the
  dataset upfront and store it straight in DRAM. Or, which is slower, generate
  each dataset item on the fly when we need it.
*/

/*
- (1) What we want to achieve with the dataset is simple. The goal is memory
      hardness, which is a property of functions that are hard to evaluate
      efficiently without a large amount of memory.

      This is pretty fitting for RandomX, as CPUs have access to memory controllers, so that means reading, writing and prefetching up to tens
      of gigabytes of DRAM.

      Let's consider two ASIC designs to beat the CPU's slow external DRAM.

- (4) An ASIC for fast mode mining at the time of RandomX's introduction
      would simply be not possible, as 2 GiBs of memory would be economically
      infeasible to store on-chip. You would lose out of the advantage of on
      chip memory, and would have to use external DRAM, then at that point
      there is no advantage to a CPU.
*/
#slide(title: [(2.RX) Memory-Hardness])[

  #uncoverb(2)[*Goal.* Sufficient memory-hardness.]
  #uncoverb(3)[
    #l-m-meta[(Let's consider two ASIC designs!)]
  ]

  #l-m-hr()

  #uncoverb(4)[
    - *(1)* 2 GiBs of on-chip low latency SRAM
      
      #uncoverb(6, l-m-meta[(An ASIC for fast mode mining is infeasible.)])
  ]
  #uncoverb(5)[
    #v(1em)
    $==>$ Try to make light mode mining viable?
    #v(1em)
  ]
]

/*
- (2) ... So, this ASIC will opt to only store the cache, and execute the
      8 superscalarhash instances. Is that much slower?

- (3) Because the superscalarhash generator, which is a CPU simulator, tries
      its hardest to maximise the dependency chain for all the registers
      across the instructions so an ASIC can't just evaluate the entire
      hash in parallel. Since each instruction depends on the previous one
      maximally, OoO execution and the superscalar nature of CPUs will be
      able to evaluate it efficiently. An ASIC would lose a lot of efficiency
      on the performance front.

- (4) Also, it uses an incredible amount of power. Equivalent to just using
      external DRAM like a regular CPU.
*/
#slide(title: [(2.RX) Memory-Hardness])[
  Let's try a competitive light mode mining ASIC?
  
  #uncoverb(2)[
    - *(2)* Light mode mining, 256 MiB of on-chip memory, 1-cycle latency for ops.
  ]

  #uncoverb(3)[
    #set text(size: 0.8em, l-m-meta-colour)

    #v(1em)

    The average SuperscalarHash function contains a total of 450 instructions, out of which 155 are 64-bit multiplications. On average, the longest dependency chain is 95 instructions long.
  
    \[...\]

    #uncoverb(4)[
      It will have to execute 155 \* 8 = 1240 64-bit multiplications per item, which will consume energy comparable to loading 64 bytes from DRAM.
    ]
  ]
  #v(1em)

  #uncoverb(2)[*Result.*] #uncoverb(5)[
    No advantage over CPU.
  ]
]

/*
- (1) So, given that we know that the Dataset takes advantage of the fact
      that CPUs are superscalar, and that Dataset initialisation is uniquely
      memory hard in the sense that creation of an ASIC that calculates the
      dataset ahead of time compared to calculating the items on demand, either
      has no advantage over a CPU.

- (2) Could we stop here? Consider an alteration of the dataset side of RandomX,
      with a new hash function that takes in a fixed key K and a large integer N,
      somehow hypothetically being an index into some dataset item.

      Assuming this is a good hash function: have we done enough?

- (3) The answer is not really, we do win memory hardness, but the fact that
      the superscalar hashes are superscalar isn't that useful. It's only to
      discourage the light mining ASIC design by burning huge amounts of energy,
      giving it no advantage over superscalar CPU designs.

      We only win memory hardness here.

      So, we need a whole other execution model, the RandomX VM, where as much
      of the CPU's capabilities are used.

- (9) Remember the goal here, we want to make the creation of an ASIC for RandomX
      as economically infeasible as possible, and which if an ASIC were to be
      created, it would resemble a CPU.

      Hence, every feature we include here that CPUs are optimised for, will
      increase the die area, the chip size, which will make it very expensive.
*/
#slide-background(
  background: image("randomx architecture dataset 1.png", fit: "cover", width: 110%, height: 110%),
  inset: 1em,
)[
  #set align(top)
  #set text(size: 0.9em)

  #grid(columns: (12fr, 10fr), gutter: 0em, gc[], gc[
    #uncoverb(2)[*Could we stop here?*]

    #uncoverb(3)[
      Not really.
    
      #l-m-meta[(Superscalar enables memory-hardness.)]
    ]

    #l-m-hr()

    #uncoverb(4)[- Superscalar instructions.]

    #uncoverb(5)[
      - Readable/writable memory.
      
        #l-m-meta[(L1, L2, L3 caches.)]
    ]

    #uncoverb(6)[
      - Instruction decoding.
      
        #l-m-meta[(μop cache)]
    ]
    
    #uncoverb(7)[
      - Floating point (IEE754), and ALU.
    ]

    #uncoverb(8)[
      - Branches/branch prediction.
    ]

    #uncoverb(9)[
      #l-m-hr()

      *Each increases die area for an ASIC!*
    ]
  ])
]

/*
- (1) Going back to the high level view, here is a recap.

      TODO
*/
#slide-background(
  background: image("randomx architecture simplified.png", fit: "cover", width: 120%, height: 120%),
)[]

#slide-background(
  background: image("randomx architecture vm.png", fit: "cover", width: 100%, height: 100%),
  inset: 1.2em
)[
  #set align(top)
  #set text(size: 0.8em)

  #grid(columns: (9fr, 12fr), gutter: 0em, gc[
  ], gc[])
]