#import "polylux/polylux.typ": *
#import "polylux/l-m.dev.typ": *

#set raw(tab-size: 4)
#show: metropolis-theme.with()
#set par(justify: true)

#let l-m-todo(body) = [#text(fill: l-m-meta-colour)[\/\/ ]#text(fill: l-m-accent-colour)[TODO: ] #text(fill: l-m-meta-colour, body)]
#let l-m-tldr(body) = [#text(fill: l-m-meta-colour)[\/\/ ]#text(fill: l-m-accent-colour)[tldr: ] #text(fill: l-m-meta-colour, body)]
#let span-sep(left, right) = box[#left #box(width: 1fr, repeat[#text(fill: l-m-meta-colour)[-]]) #right]

#show math.equation: set text(1.25em)

#let l-m-meta(body) = text(fill: l-m-meta-colour, body)
#let l-m-code(body) = text(fill: l-m-code-colour, body)

#let uncoverb(b, body) = uncover((beginning: b), body)

#let gc = block.with(
  width: 100%,
  height: 100%,
)

#let gh = block.with(
  width: 100%,
)

/*
- TODO: after practicing, you figure out the time and where to cut.
        2025-10-27 We are basically finished with everything!!
*/

/*
- TODO: absolutely make references to floating point handbook
        make references to the PDF talk presented as well
*/
/*
- TODO: finish the ~2 slides for intro and the conclusion.
*/

#title-slide({
  l-m-title("Zero to RandomX.js:")
  linebreak()
  l-m-title("Bringing Webmining Back From The Grave")
  l-m-hr()
  set text(size: 0.8em)
  text(fill: l-m-meta-colour, "Tuesday, October 3rd | Lecture Theatre 123 | 6 PM - 8 PM")
})

#slide(title: "About me")[
  - Liam, l-m, #underline[l-m.dev], #underline[l-m\@l-m.dev]
]

#slide(title: "This Talk?")[
	#l-m-todo[(1.POW) Explain POW consensus, ASICs?]

	#l-m-todo[(2.RX) Explain RandomX.]

	#l-m-todo[(3.JS) Introduce RandomX.js]

	#l-m-todo[(4.FP) Explain the semifloat impl. in RandomX.js]
]

#new-section-slide[(1.POW) Proof-of-Work Consensus]

#new-section-slide[(2.RX) RandomX]
    
/*
- (3) By then, ASICs for cryptonight have already been created, so the switch was needed.
*/
#slide(title: [(2.RX) RandomX])[

  RandomX is a proof-of-work algorithm that is optimized for general-purpose CPUs. It has stood the test of time as an *ASIC resistant* hash function.

  #uncover((2, 3))[
    On November 30th, 2019, Monero switched from its old POW algorithm, _cryptonight_, to RandomX. #uncover(3)[
      #text(fill: rgb("#f26822"))[Which had already been broken.]
    ]
  ]

  #uncover(3)[
    #l-m-hr()
    #quote(attribution: [tevador/RandomX], block: true)[
      RandomX uses random code execution (hence the name) together with several memory-hard techniques to minimize the efficiency advantage of specialized hardware.
    ]

    #l-m-meta[(Reminder: the goal is to make the CPU the perfect ASIC.)]

    #v(1em)

    https://github.com/tevador/RandomX
  ]
]

/*
- This is RandomX on a high level. This is supposed to resemble a CPU and this is supposed to be 2 GiB
  of fixed read only memory for it to sample from.

  The hash function accepts two input values:

  - String K with a size of 0-60 bytes (key)
  - String H of arbitrary length (the value to be hashed)

  and outputs a 256-bit result R.

  Intended use states that you fix the key, and you build the dataset from that which can take multiple
  seconds. Once the key is fixed you can use it like a regular hash function.

  You can think of these as two separate units, black boxes. The only thing the VM will
  ask the dataset is to read its items, which are 64 bytes in length each.

  As you can see in the corner there, the VM has a 2 KiB scratchpad which is basically its working
  memory, which is divvied up into L1, L2, L3. The point of the VM is to blast the scratchpad with entropy
  and then hash it along with it's registers. That's the final result.

  So what I'm going to do is look at these in separate pieces.
*/
#slide(
  background: image("randomx architecture simplified.png", fit: "cover", width: 120%, height: 120%),
)[]

/*
- (3) A hint here is that you actually don't need to lug around 2 GiB dataset, you can generate it on
      the fly from the dataset cache, which is only 256 MiBs.

      If you want to mine fast, you generate the entire 2 GiBs up front, but, if you just want to mine
      on a memory budget or verify someones hash, you only need the 256 MiB "cache" as you can run
      the 8 hash functions on demand. This is called light-verification, or light-mode.

      The most important thing to take from this slide is that the RandomX VM will ask for items,
      and those items are generated by executing 8 hash functions derived from the key.
      So these hash functions are generated just in time, they're just programs.
*/
#slide(
  background: image("randomx architecture dataset.png", fit: "cover", width: 110%, height: 110%),
  inset: 1.2em
)[
  #set align(top)
  #set text(size: 0.8em)

  #grid(columns: (10fr, 9fr), gutter: 0em, gc[], gc[
    #uncover((2, 3))[
      Pre-initialisation.

      - The key $K$ is passed to the SSH generator, which generates 8 hash functions.
      - $K$ is also used to fill 256 MiBs of static memory.
    ]

    #uncover(3)[
      #l-m-hr()
      Dataset-initialisation.

      - Each 64-byte Dataset item is generated by executing each of those 8 functions, and XORing data from the cache.
      - Cache $==>$ Dataset.
    ]
  ])
]

/*
*/
#slide(title: [(2.RX) Superscalar?], inset: 1em)[
  #set align(top)

  CPUs are _very_ good at executing arbitrary code.

  #grid(columns: (5fr, 4fr), gutter: 1em, gh[
    #set align(top)
    #v(1em)
    
    ```yasm
        add rax, rbx      ; (1) a = a + b
        imul rcx, rdx     ; (2) c = c * d
        sub rbx, 5        ; (3) b = b - 5
    ```
    #uncover((2, 3, 4, 5, 6, 7))[
      ```yasm
          ; (1) (2) (3) executed all at once (superscalar)
      ```
    ]
    ```yasm
        and rax, rcx      ; (4) a = a & c
        cmp rbx, 0        ; (5) test b with 0
    ```
    #uncover((3, 4, 5, 6, 7))[
    ```yasm
        ; (3) -> (5). (OoO-execution)
    ```
    ]
    
  ], gh[
    #v(1em)

    #uncover((4, 5, 6, 7))[
      ```yasm
        ; OoO, bundle (3) with (5).
        ; superscalar, execute both bundles at once
        add rax, rbx      ; (1) a = a + b
        imul rcx, rdx     ; (2) c = c * d
        and rax, rcx      ; (4) a = a & c

        sub rbx, 5        ; (3) b = b - 5
        cmp rbx, 0        ; (5) test b with 0
      ```
    ]
  ])
  #uncover((4, 5, 6, 7))[
    #l-m-hr()
  ]
  #grid(columns: (5fr, 4fr), gutter: 1em, gc[
    ```yasm

        jg l0             ; (6) if (b > 0) goto l0;
        mov rdx, rax      ; (7) d = a
    l0:
        xor rax, rax      ; (8) a = 0
    ```
    #uncover((5, 6, 7))[
      ```yasm
          ; (BP and speculative execution)
          ; at (6), optimistically guess that (b > 0) and
          ; skip straight to executing (8), aborting if wrong
      ```
    ]
  ], gc[
    #uncover((6, 7))[
      ```yasm

          add rax, rbx   ; writes to rax
          ;                ... code that uses rax
          mov rax, 5     ; also writes to rax
          ;                ... code that uses rax
      ```
    ]
    #uncover(7)[
      ```yasm


          ; RR will rename rax -> r0, execute the
          ; mov bundle with the add bundle.
      ```
    ]    
  ])
]

/*
- (1) If you didn't get all that, that's okay. The important things to take away is that CPU's are:
- (6) ... this to drive away ASICs. I'll give an example of how SuperscalarHash function is generated.
*/
#slide(title: [(2.RX) Superscalar?], inset: 2em)[
  CPUs are:

  #uncover((2, 3, 4, 5, 6))[
    1. Superscalar #l-m-meta[(execute multiple instructions at once)]
  ]
  #uncover((3, 4, 5, 6))[
    2. OoO-execution #l-m-meta[(reorder instructions)]
  ]
  #uncover((4, 5, 6))[
    3. Speculative execution #l-m-meta[(optimistically guess branches)]
  ]
  #uncover((5, 6))[
    4. Register renaming #l-m-meta[(more registers than it seems)]
  ]

  #uncover(6)[
    #v(1em)
    All of these increase Instruction-Level-Parallelism (ILP).
    
    #l-m-hr()

    Generated code in RandomX needs to take advantage of this!
  ]
]

/*
- CPU ..., generating code to saturate its ALU.

- NOTE: These are integer instructions only! The RandomX VM also uses floating point.
*/
#slide(title: [(2.RX) Maximising ILP])[
  #quote(block: true, attribution: [6\. SuperscalarHash (spec)])[SuperscalarHash is a custom diffusion function that was designed to burn as much power as possible using only the CPU's integer ALUs.]

  #v(1em)
  
  - RandomX wants to increase ILP,
  - so superscalarhash-functions are generated by simulating a reference superscalar CPU #l-m-meta[(Intel Ivy Bridge µarch)].

  #l-m-hr()

  - It assumes a CPU with 3 parallel integer execution ports (P0, P1, P5).

    #l-m-meta[(Multiplication can only run on P5, etc.)]
    
  - Schedules an instruction on every available port, for every cycle.
]
/* TODO: add in uncover */


/* REMARK 1:

  - So far this is pretty garbage, I don't actually explain what an ASIC is, or really explain what a CPU really does.
    Honestly, to avoid critisism, remove the Superscalar OoO, etc where I show off the x86 ASM.

  - Superscalarhash is explained really poorly, even up to the next part. Might need a buffer slide honestly.
  - Everything to do with the dataset is pretty bad.
*/

/*
- (1) After each execution of a SuperscalarHash, the next cache index is set to the register that has the
      longest dependency chain in that superscalarhash to minimise how much a would be ASIC could
      parallelise the execution of the hash and force execution to be overall a straight line where
      CPUs excel.

- (2) And that's it! This is the entire Dataset side of RandomX. If you want to do light-mining or
      verification, the RandomX VM will call this `getItem` every time it needs to access the dataset.

      If you're not doing light-verfication and want to mine, just generate all of the 2 GiB dataset
      items ahead of time, which will take a couple seconds.

- (3) If you think that we could stop here and make this our RandomX, as it's pretty good already,
      know that this minus the cache is a part of what Tor uses for it's client puzzles. All the
      techniques for burning through a CPUs ILP is replicated in Equi-X, among others.
*/
#slide(title: [(2.RX) SuperscalarHash], inset: 1em)[
  #set align(top)

  #grid(columns: (5fr, 4fr), gutter: 1em, gc[
    = *Algorithm.*

    #v(1em)

    ```
    cacheIndex = item number
    r0 = (item number + 1) * 6364136223846793005
    r1 = r0 ^ 9298411001130361340
    
    i = 0
    do {
        block = cache[cacheIndex % nr. 64 bytes in cache]
        SuperscalarHash[i](r0, r1, r2, r3, r4, r5, r6, r7)
        r0..7 ^= block[0..7]
        cacheIndex = r[longest dependency chain]
        i = i + 1
    } while(i < 8)

    item data = (r0|r1|r2|r3|r4|r5|r6|r7)
    ```

    #uncover((2, 3))[
      #l-m-hr()    
      #l-m-meta[(That's really all there is to the Dataset.)]
    ]
    #uncover(3)[

      https://github.com/tevador/equix #l-m-meta[(Tor)]
    ]
  ], gc[
      #set text(size: 0.8em)
      ```yasm
      getItem:
        ; r0 = (itemNumber + 1) * 6364136223846793005
        mov r8, rdi
        add r8, 1
        mov rax, 6364136223846793005
        imul r8, rax

        ; r1 = r0 ^ 9298411001130361340 ... and so on for r2-r7
        mov r9, -9148333072579190276   ;
        xor r9, r8                     ; r9 (r1) = r0 ^ constant
        mov r10, -6381431487974942650  ;
        xor r10, r8                    ; r10 (r2) = r0 ^ constant
        ; ...
        ; ...
        ;
        ; execute SuperscalarHash[i](r0, ..., r7)

        ; each invocation is unrolled in the generated code,
        ; no loop here.
        imul r12, r15             ; IMUL_R r4, r7
        imul r13, r14             ; IMUL_R r5, r6
        imul r10, r11             ; IMUL_R r2, r3
        lea r14, [r14 + r11*2]    ; IADD_RS r6, r3 (shift 1)
        xor r15, r9               ; IXOR_R r7, r1
        mov rax, -1727223807      ;
        xor r8, rax               ; IXOR_C r0, imm32
        sub r15, r14              ; ISUB_R r7, r6 (going down ↓)
        ; ...................
      ```
  ])
]

/*
- So, to recap:
*/
#slide(
  background: image("randomx architecture dataset.png", fit: "cover", width: 110%, height: 110%),
  inset: 1.2em
)[
  #set align(top)
  #set text(size: 0.8em)

  #grid(columns: (10fr, 9fr), gutter: 0em, gc[], gc[
    Pre-initialisation.

    - The key $K$ is passed to the SSH generator, which generates 8 hash functions.
    - $K$ is also used to fill 256 MiBs of static memory.

    #l-m-hr()
    Dataset-initialisation.

    - Each 64-byte Dataset item is generated by executing each of those 8 functions, and XORing data from the cache.
    - Cache $==>$ Dataset.
  ])
]
/*
- An important thing to remmeber here is that we can generate the 2 GiBs of the
  dataset upfront and store it straight in DRAM. Or, which is slower, generate
  each dataset item on the fly when we need it.
*/

/*
- (2) What we want to achieve with the dataset is simple. The goal is
      memory hardness, which is a property of functions that are hard
      to evaluate efficiently without a large amount of memory.

      - REMARK 1. This should act like a barrier, if you reduce the amount
        of memory that you use, performance should drop off drastically.

      This is pretty fitting for RandomX, as CPUs have access to memory
      controllers, so that means reading, writing and prefetching up to
      tens of gigabytes of DRAM.

- (3) Let's consider the two ASIC designs proposed by RandomX developers
      to try beat the CPU's slow external DRAM, so the goal is to somehow
      put the memory on-chip.

- (4)
- (5) An ASIC for fast mode mining at the time of RandomX's introduction
      would simply be not possible, as 2 GiBs of memory would be 
      economically infeasible to store on-chip. You would lose out of the 
      advantage of on chip memory, and would have to use external DRAM, 
      then at that point there is no advantage to a CPU.
*/
#slide(title: [(2.RX) Memory-Hardness])[

  #uncoverb(2)[*Goal.* Sufficient memory-hardness.]
  #uncoverb(3)[
    #l-m-meta[(Let's consider two ASIC designs!)]
  ]

  #l-m-hr()

  #uncoverb(4)[
    - *(1)* 2 GiBs of on-chip low latency SRAM
      
      #uncoverb(5, l-m-meta[(An ASIC for fast mode mining is infeasible.)])
  ]
  #uncoverb(6)[
    #v(1em)
    $==>$ Try to make light mode mining viable?
    #v(1em)
  ]
]

/*
- (2) ... So, this ASIC will only store the cache, and execute the
      8 superscalarhash instances. Is that much slower?

- (3) Because the superscalarhash generator, which is a CPU simulator, 
      tries its hardest to maximise the dependency chain for all the 
      registers across the instructions so an ASIC can't just evaluate the 
      entire hash in parallel. Since each instruction depends on the 
      previous one maximally, OoO execution and the superscalar nature of 
      CPUs will be able to evaluate it efficiently. An ASIC would lose a 
      lot of efficiency on the performance front.

- (4) Also, it uses an incredible amount of power. Equivalent to just using
      external DRAM like a regular CPU.

- (5) No advantage over CPU, not in speed, or even in energy usage. Hence,
      this insentivises any ASIC to use external DRAM like CPUs. So 
      RandomX actually succeeds in being memory hard.

      REMARK 1: another slide section about saying yay memory hard!
*/
#slide(title: [(2.RX) Memory-Hardness])[
  Let's try a competitive light mode mining ASIC?
  
  #uncoverb(2)[
    - *(2)* Light mode mining, 256 MiB of on-chip memory, 1-cycle latency for ops.
  ]

  #uncoverb(3)[
    #set text(size: 1em, l-m-meta-colour)

    #v(1em)

    The average SuperscalarHash function contains a total of 450 instructions, out of which 155 are 64-bit multiplications. On average, the longest dependency chain is 95 instructions long.
  
    \[...\]

    #uncoverb(4)[
      It will have to execute 155 \* 8 = 1240 64-bit multiplications per item, which will consume energy comparable to loading 64 bytes from DRAM.
    ]
  ]
  #v(1em)

  #uncoverb(2)[*Result.*] #uncoverb(5)[
    No advantage over CPU.
  ]
]

/*
- (1) So, given that we know that the Dataset takes advantage of the fact
      that CPUs are superscalar, and that Dataset initialisation is uniquely
      memory hard in the sense that creation of an ASIC that calculates the
      dataset ahead of time compared to calculating the items on demand, either
      has no advantage over a CPU.

      REMARK 1: this is written really poorly ^^^

- (2) Could we stop here? Consider an alteration of the dataset side of RandomX,
      with a new hash function that takes in a fixed key K and a large integer N,
      somehow hypothetically being an index into some dataset item.

      Assuming this is a good hash function: have we done enough?

- (3) The answer is not really, we do win memory hardness, but the fact that
      the superscalar hashes are superscalar isn't that useful. It's only to
      discourage the light mining ASIC design by burning huge amounts of energy,
      giving it no advantage over superscalar CPU designs.

      We only win memory hardness here.

      So, we need a whole other execution model, the RandomX VM, where as much
      of the CPU's capabilities are used.
- (4) ... lists (5), (6), ..

- (9) Remember the goal here, we want to make the creation of an ASIC for RandomX
      as economically infeasible as possible, and which if an ASIC were to be
      created, it would resemble a CPU.

      Hence, every feature we include here that CPUs already have will
      increase the die area, the chip size, which will make it very expensive to
      manufacture a custom ASIC.
*/
#slide(
  background: image("randomx architecture dataset 1.png", fit: "cover", width: 110%, height: 110%),
  inset: 1em,
)[
  #set align(top)
  #set text(size: 0.9em)

  #grid(columns: (12fr, 10fr), gutter: 0em, gc[], gc[
    #uncoverb(2)[*Could we stop here?*]

    #uncoverb(3)[
      Not really.
    
      #l-m-meta[(Superscalar enables memory-hardness.)]

      #l-m-hr()
    ]

    #uncoverb(4)[
      #list[Superscalar instructions.]
    ]

    #uncoverb(5)[
      #list[Readable/writable memory.
        
        #l-m-meta[(L1, L2, L3 caches.)]
      ]
    ]


    #uncoverb(6)[
      #list[Instruction decoding.
      
        #l-m-meta[(μop cache)]
      ]
    ]
    
    #uncoverb(7)[
      #list[Floating point (IEEE754), SIMD, (more) ALU.]
    ]

    #uncoverb(8)[
      #list[Branches/branch prediction.]
    ]

    #uncoverb(9)[
      #list[Native AES.]
    ]

    #uncoverb(10)[
      #l-m-hr()

      *Each increases die area for an ASIC!*
    ]
  ])
]

/*
- (1) Going back to the high level view, here is a recap.
      
      TODO
*/
#slide(
  background: image("randomx architecture simplified.png", fit: "cover", width: 120%, height: 120%),
)[]

/*
- (1) We have that they RandomX virtual machine is only concerned with the
      input hash bytes, not so much the key.

      On a high level there are four main sections of the VM, which are the
      scratchpad (which is the working memory of this imaginary CPU), the
      program buffer (which just holds the instructions), the register file,
      and the abstract virtual machine which describes the way to execute
      each program.

      You can follow the yellow lines as the flow of initialisation bytes,
      and the purple lines as the result flow, like the image for the dataset.

- (2) I will go through the general algorithm, and make note of some of the
      cryptographic primitives used.

- (3) An initial seed is calculated by hasing the input using Blake2b, then
      the scratchpad is entirely filled from random bytes using AesGenerator1R,
      which is a RandomX specific random bytes generator that uses one round
      of AES to mix up the state.

- (4) The program buffer is filled, which is basically all the state needed
      to program an instance of the RandomX virtual machine. 128 bytes are
      set aside to be loaded into the register file, and 2048 bytes is the
      actual program.

      This uses AesGenerator4R, which is the same as 1R, but uses 4 rounds
      of AES. The previous state of the 1R generator is fed into the 4R
      generator.

      An important thing to note is the choice of using AES here, most CPUs
      have a native instruction set for calculating AES rounds (AES-NI on
      Intel, same exists for Arm and Risc-V), which we mentioned before.

      The AES generators are sufficient in an avalanche of the input bits,
      but, the generator is reversible and doesn't make for a good hash
      function, which is why it is always initialised with a non-reversible
      hash function which is Blake2b with the seed there.

      The VM is executed along with all the instructions, filling up the
      scratchpad and register files with entropy, and reading from the
      dataset. I'll explain the instruction set later on.

      Last, the register file is hashed with Blake2b and copied to the
      AesGenerator4R* state which we're keeping around to generate
      an entirely new program, going around steps 3-5 again.

      The important thing to note here, is that we execute 8 randomly
      generated programs, where the output of one program is used to
      generate the program after. The reasons for this will come in
      the next slide.

- (5) So after we executed the 8 programs, we have a scratchpad which
      is just filled with entropy, so we hash it using the 1R generator
      (which is fast), and the final result is calculated as the hash of
      the scratchpad with a portion of the register file with Blake2b.
*/
#slide(
  background: move(dy: 8pt, image("randomx architecture vm.png", fit: "cover", width: 100%, height: 100%)),
  inset: 1.2em
)[
  #set align(top)
  #set text(size: 0.8em)

  #grid(columns: (17fr, 24fr), gutter: 0em, gc[
    #uncoverb(2)[
      *Algorithm.*
    ]

    #uncoverb(3)[
      1. Initial seed S is calculated. #l-m-meta[(Blake2b)]
      2. Scratchpad is filled. #l-m-meta[(AesGenerator1R=S)]
    ]

    #uncoverb(4)[
      #l-m-hr()

      3. Program Buffer filled. #l-m-meta[(AesGenerator4R\*)]

        #l-m-meta[(VM is programmed from contents)]
      
      4. *The VM is executed.*
      5. Register file is hashed and copied to AesGenerator4R\* state.
      6. Steps 3-5 are performed *8* times.

        #l-m-meta[(chained VM execution)]
    ]

    #uncoverb(5)[
      #l-m-hr()

      7. Scratchpad fingerprint is calculated. #l-m-meta[(AesGenerator1R)]
      
      8. Final result R is the hash of scratchpad fingerprint + register file. #l-m-meta[(Blake2b)]
    ]
  ], gc[])
]

/*
- (1) There is a very good reason RandomX opts to execute 8 different
      programs in a chain.

- (2) Remember that mining is simply just finding an integer called
      the nonce that when you concat the block data, which is the 
      transactions, with the nonce it hashes to a value that is 
      acceptible, within a certain difficulty.

- (3) Given this, since the nonce can be any number, why not just
      optimise for the easy programs, and skip the hard ones?

- (4) Well, if you had to execute multiple programs in a chain, aborting
      on an unfavourable program would be pretty expensive because you'd
      have to throw away all your previous work. Even if you were quicker
      at the easy programs, the fact that you need to do 8 whittles down
      your advantage back to nothing.

      So, RandomX doing 8 chained programs in a row means that you're 
      forced to commit to executing them all, otherwise you'd be much
      slower than just biting the bullet and doing it the honest way.
*/
#slide(
  background: move(dy: 25%, image("randomx easy program problem.png", fit: "contain", width: 100%, height: 100%)),
  title: [(2.RX) Easy program problem],
)[
  #set align(top)

  #gc[
    #uncoverb(2)[
      - Mining is evaluating HASH(block $⊕$ nonce), where nonce = 0, 1, 2, ...

        #l-m-meta[(until a successful hash is found.)]
    ]

    #uncoverb(3)[#list[Why not just nonce++ when an unfavorable #l-m-meta[(hard)] program is found?]]
    
    #uncoverb(4)[
      #l-m-hr()

      *Reason.* Chaining programs forces you to commit, or take a #l-m-meta[(time)] penalty.
    ]
  ]
]

/*
- (1) So, we are memory hard, but that's only for reading, so we're not
      taking advantage of the caches that exist in a CPU already.

- (2) Remember that CPUs have caches for frequently acccessed memory, and
      in basically all CPUs it's organised into an L1, L2, L3 hierarchy,
      with L1 being the closest to a core often being exclusively owned
      by a core, L2 being larger and slightly slower, holding data evicted
      by L1, and L3 being the largest and shared among most or all cores.

      REMARK 1: A lot of this needs to be simplified, at the end of the
        day, not a lot of people would actually know about this stuff

- (3) Every instruction that can read or write will do so respecting the
      hierarchy, so accesses to L1 are done 3 times as much as accesses to
      L2, and accesses to L3 are done sparingly and at certain stages to
      avoid stalls.

- (4) The image below shows the distribution of writes to the scratchpad,
      it's divided up into three sections with the far left being L1,
      middle left being L2, and the entire right being L3. Each red pixel
      represents 8 bytes being overwritten.
*/
#slide(
  title: [(2.RX) Scratchpad],
)[
  - Memory-hard, but don't R/W? #l-m-meta[(Forgetting L1, L2, L3?)]
  
  #uncoverb(2)[
    #l-m-hr()
    
    #list[The scratchpad is meant to mirror L1, L2, L3 present in typical CPUs.]
  ]

  #uncoverb(3)[
    - Each inst. that can R/W, will do so respecting the hierarchy.

      16 KiBs #l-m-meta[(L1)] $subset.eq$ 256 KiBs #l-m-meta[(L2)] $subset.eq$ 2 MiBs #l-m-meta[(L3)]
  ]
  

  #uncoverb(4)[
    #l-m-hr()
    #set align(center)
    #image("L1 L2 L3.png", width: 80%)
  ]
]

/*
- (1) The virtual machine has 8 integer registers r0-r7 and a total of 12
      floating point registers split into 3 groups, f0-f3, e0-e3, a0-a3.
      Group R registers are 64 bits wide, and each floating point register
      is 128 bits wide, which transparently is just a pair of two doubles
      that aren't separately addressible, so operations on the VM's FP
      registers can be compiled down to operations on SIMD registers.

      The FP registers a0-a3 are fixed from when the VM was programmed.
      You could view the f0-f3 registers as "additive" registers and,
      e0-e3 as "multiplicative" registers.

      There are also 3 internal registers, ma, mx, and fprc. You might have
      already seen ma and mx, they're the registers that store an index
      into the dataset item to access.

      fprc is a special register which denotes the current 4 rounding 
      modes, I'll talk about this more as well as the FP register classes 
      when later on.

      amd64 is the lowest common denominator over all of the ISAs RandomX
      wants to support, so only 8 integer registers and 12 SIMD registers,
      and all of the VM instructions are two address x86 style, so two
      operand, writing to the first one. All of the other ISAs, like Risc-V
      and Arm have more integer registers and support actual
      three address code.

      REMARK 1:
        MUUUUUUUCH simpler, cut down by 1/2. You're talking way too long with
        nothing going on in the slides. People want to hear you talk, and while
        you talk, generally it must show up on the slides.

- (2) The integer instructions are pretty standard...

      No division is included, but IMUL_RCP is multiplication by the
      a reciprocal, so division by some fixed 32 bit value. The reason
      being is division exists on CPUs, but isn't pipelined/fast, but
      you wouldn't want to exclude division. Calculating the reciprocal
      requires a division, so including IMUL_RCP forces ASICs to include
      a division circuit which CPUs already have.

      Note that most of these instructions have _R and _M variants, which
      read and write registers, or read and write to the scratchpad.

      TODO:

- (3) The only floating point operations that are included are the
      base deterministic IEEE754 instructions, swapping the pair within
      an FP register, and FSCAL which performs a scaling according to
      some complex rules which is equivalent to a XOR on the floating
      point binary representation.

      The reason why FSCAL exists, which works on the F registers, is so
      that ASICs can't use a quicker fixed point representation over using
      IEEE doubles. If they used a fixed point representation, they'd need
      to follow the complex scaling rules, where if it's in IEEE format,
      a simple XOR gives it to you for free.

- (4) Stores into the scratchpad are done with ISTORE. Loops are implemented
      using CBRANCH, and the generation is set up in a way so that upwards
      branches don't nest, and infinite loops can't happen.

      Superscalar designs CPU designs have a huge advantage here executing
      the code with the FP and integer instructions, as well as speculative
      execution around branches.

      The CFROUND instruction adjusts the rounding mode of the add, sub,
      mul, div, and square root, just the IEEE instructions. The default
      setting of fprc is zero, which is the default assumed rounding mode 
      for basically all programming languages.

*/
#slide(title: [(2.RX) Instructions + Registers], inset: 1.2em)[
  #let gb = gc.with(height: 60%)

  #set align(top)
  
  #grid(columns: (10fr, 10fr), gutter: 1em, gb[
    #uncoverb(2)[
      *Instructions (integer).*

      - IADD, ISUB, IMUL, IMULH, ISMULH, INEG
      - IXOR, IROL, ISWAP_R
      - IMUL_RCP #l-m-code[(division by imm32)]
    ]

    #uncoverb(3)[
      #l-m-hr()
      
      *Instructions (FP).*

      #l-m-meta[(IEEE754)] FADD, FSUB, FMUL, FDIV, FSQRT

      - FSWAP_R: #l-m-code[(dst0, dst1) = (dst1, dst0)]
      - FSCAL_R: #l-m-code[(XOR by 0x80F0000000000000)]
    ]
  ], gb[
    #uncoverb(4)[
      *Instructions (misc).*
      - ISTORE: _arbitrary_ scratchpad addr.

      - CBRANCH: backwards branch, flat loops
      - CFROUND: change FP rounding #l-m-meta[(IEEE754)]

        (adjusts *fprc* = 0, 1, 2, 3)

      #[
        #set text(size: 0.8em)
        #set align(center)

        #table(
          columns: (auto, auto),
          stroke: luma(70),

          [0], [roundTiesToEven],
          [1], [roundTowardNegative],
          [2], [roundTowardPositive],
          [3], [roundTowardZero],
        )
      ]
    ]
  ])

  #[
    #set align(right)
    #uncoverb(2)[
      #l-m-meta[(most instructions have \*\_R, \*\_M variants)]
    ]
    #linebreak()
  ]
  
  #block[
    #set align(left)
    #let sz(d) = (auto,) * d
    #set par(spacing: 0pt)
    #let except(d, i) = (x, _) => if x == i {} else {d}
    #let initsp = 12em

    #table(
      columns: (initsp,) + sz(8),
      stroke: except(l-m-meta-colour, 0),
      fill: except(rgb("#ff000075"), 0),
    )[#l-m-meta[(64-bit integers)]][r0][r1][r2][r3][r4][r5][r6][r7]

    #table(
      columns: (initsp,) + sz(12),
      stroke: except(l-m-meta-colour, 0),
      fill: (x, _) => {
        if x == 0 {}
        else if x <= 4 { rgb("#016fff56") }
        else if x <= 8 { rgb("#01ff7356") }
        else { rgb("#ff01ff56") }
      }
    )[#l-m-meta[(pairs of doubles)]][f0][f1][f2][f3][e0][e1][e2][e3][a0][a1][a2][a3]

    #table(
      columns: (initsp,) + sz(3),
      stroke: except(l-m-meta-colour, 0),
    )[#l-m-meta[(misc)]][ma][mx][fprc]
  ]
]

#let Ru = math.upright("R")
#let RD = $upright(bold("RD"))$
#let RU = $upright(bold("RU"))$
#let RN = $upright(bold("RN"))$
#let RZ = $upright(bold("RZ"))$

/*
- (1) Before I conclude, I want to go over floating point numbers and give am
      explaination of why RandomX would even want to use these, given that
      they have a track record of feeling "nondeterministic" or "random".

- (2) The most common example is 0.1 + 0.2 != 0.3. This sets a lot of people
      off because this is just not what you should be expecting at all.
      Numbers are numbers, so why are floats just lying here?

- (3) The easiest way to explain this is just that a floating point numbers
      make a tradeoff between performance and ease of use, over actually
      representing the numbers they represent.

      The floating point standard IEEE754 for double precision, which is what
      we care about in this presentation, uses in short, base 2 numbers in
      scientific notation. So the only numbers that you write down in your 
      programs that are strings of integer powers of 2, those are the only ones
      that can actually be exactly represented.

      REMARK 1: actually show this.... wtf

- (4) Simplifying a lot, because of maths, representing an arbitrary real 
      number
      takes an infinite amount of space. Imagine a number line, and you just
      pointed to a random number on it. If you picked that real number at 
      random, the chances that it is a number that can be represented in a 
      finite amount of space is actually zero.

      We don't have an infinite amout of memory, so representing real numbers 
      exactly is just not possible.

      IEEE754 double precision defines a 64 bit wide floating point number, so 
      there is only less than 2^64 possible numbers compared to the infinite 
      amount of real numbers. For simplicity, and because RandomX doesn't need 
      it, we don't consider NaN here.

- (5) We also have that the set of floating point doubles R contains positive 
      and negative infinity.

- (6) So to recap, ...

- (7) But, I haven't actually addressed the elephant in the room, which is that
      programmers working with floating point numbers find it frustrating,
      inaccurate, and basically a random black box.

      If floating point feels random and like magic, why should RandomX rely on it to give consistent results?
*/
#slide(title: [(2.RX) IEEE754])[
  #uncoverb(2)[
    - 0.1 + 0.2 = 0.30000000000000004 != 0.3 #l-m-meta[(?? wtf)]
  ]

  #uncoverb(3)[
    - *IEEE754* makes a _tradeoff_. #uncoverb(4)[Define $Ru$ as set of _doubles_ without NaN. Then $|Ru| < 2^64$.]

      #uncoverb(5)[Define $RR^infinity = RR union { +infinity, -infinity}$, then $Ru subset RR^infinity$. #l-m-meta[(this is just $overline(RR)$)]]
  ]

  #uncoverb(6)[
    #l-m-hr()

    *Result.* $Ru$ is a finite amount of useful numbers, with $plus.minus infinity$. #l-m-meta[(IEEE754)]
  ]

  #linebreak()

  #uncoverb(7)[
    #figure[
      But... what about inaccuracies, rounding? FP is random??
    ]
  ]
  /* REMARK 1: probably change the above to be not innacuracies, that's a given.
      change it to probably more so FP is random? how is FP the same on all PCs? */
]

/*
  REMARK 1:
    I seriously give zero explaination why it is not random, and specified well.
*/

/*
- (2) What does correctly rounded mean? It basically is, take two numbers,
      do an operation with infinite precision, like mathematical addition, 
      then round it down back into a floating point number.
      

      The 5 core operations of IEEE754 are defined this way, for example
      addition of x and y is just taking those two numbers, adding them
      as you would like real numbers, then rounding down which will basically
      crunch the number back to something within range that the double can
      actually represent.

- (3) There are actually 4 different ways to round a number so that it goes back
      into being a double. All of them are specified by IEEE, which are
      - round to nearest,
      - round towards negative infinity,
      - round towards positive infnity,
      - round towards zero.
      
- (4) If you do any of these primitive operations on floats, you can expect the
      CPU to round your numbers according to these 4 different rounding modes,
      which there is usually an inbuilt register inside your CPU to select a
      rounding mode globally, not per instruction.

      So, the RandomX "fprc" is an integer from 0-3 which stores the current
      rounding mode, and the floating point instructions defined a couple slides
      ago use the global rounding mode.

      CPUs already have these 4 rounding modes, and there is a lot of die space
      on them dedicated to performing the 5 operations, so if RandomX only used
      round to nearest, it would be missing out.

      Also the fact that fprc is global, it's not per instruction. So the CPUs
      have this internal register state which can be modified to switch out
      entire circuits at runtime, which ASICs would need to add.

- (5) Now, an important thing to understand is that if you have any experience
      with programming languages like python, javascript, or rust, all of them
      only ever provide RN and most people don't think that the others exist.

      In javascript, you just can't get other rounding modes, and python and
      rust you need external bindings. In rust, it's actually undefined 
      behaviour if you are to modify the global rounding mode.
      
      This would be a problem if you are going to implement RandomX in one of
      those languages.

      So what you need to take away from this slide, is that floating point
      numbers are under IEEE754 are perfectly defined and portable, they just
      have a decent amount of internal machinery to do with rounding.
*/
#slide(title: [(2.RX) IEEE754])[
  #gh(height: 60%)[
    FP is perfectly specified, with $+$, $-$, $times$, $div$, $sqrt(x)$ *correctly rounded*.

    #uncoverb(2)[
      - $mono("fadd_0")(x, y) = RN(x + y)$, $mono("fsqrt_0")(x) = RN(sqrt(x))$, etc.
    ]

    #uncoverb(4)[
      #l-m-hr()

      Define $circle.small : RR^infinity -> Ru$ to be a function that rounds according to a #l-m-meta[(global)] fprc.

      - $"fadd"(x, y) = circle.small(x + y)$, $"fsqrt"(x) = circle.small(sqrt(x))$, etc.
    ]

    #v(1em)

    #uncover(5)[
      #figure[
        *All P/L give you $RN$ only.* \
        #l-m-meta[(foreshadowing)]
      ]
    ]
  ]

  #grid(columns: (10fr, 10fr), gutter: 1em, gh[
    #uncoverb(4)[
      ```
      ○(x) {
        case fprc = 0: RN(x)
        case fprc = 1: RD(x)
        case fprc = 2: RU(x)
        case fprc = 3: RZ(x)
      }
      ```
    ]
  ], gh[
    #set text(size: 0.8em)
    #set align(right)
    
    #uncoverb(2)[
      #table(
        columns: (auto, auto, auto),
        stroke: luma(70),
        align: left,

        table.header(
          [*fprc*]
        ),
        [0], [roundTiesToEven], [$RN : RR^infinity  -> Ru$],
        [1], [roundTowardNegative], [$RD : RR^infinity -> Ru$],
        [2], [roundTowardPositive], [$RU : RR^infinity -> Ru$],
        [3], [roundTowardZero], [$RZ : RR^infinity -> Ru$],
      )
    ]
  ])
]

/*
- (1) Calling back to the first slide in this part...
*/
#slide(title: [(2.RX) Conclusion])[
  #quote(attribution: [tevador/RandomX], block: true)[
    RandomX uses random code execution (hence the name) together with several memory-hard techniques to minimize the efficiency advantage of specialized hardware.
  ]

  #l-m-meta[(Reminder: the goal is to make the CPU the perfect ASIC.)]

  #l-m-hr()

  #grid(columns: (13fr, 9fr), gutter: 1em, gh[
    #uncoverb(2)[
      An ASIC for RandomX needs:

      - 2 GiBs of #l-m-meta[(external)] DRAM - *Memory-hard*
      - *Random* code execution.
      - Superscalar design, instruction/μop cache.
      - Speculative execution, branches.
      - Full compliant IEEE754.
      - Hardware dividers.
      - Hardware AES, SIMD floating point.
      - 2 MiBs of scratchpad (L1, L2, L3).
    ]
  ], gh[
    #uncoverb(3)[
      *Verdict.* No advantage over CPU.

      #l-m-meta[(economically infeasible)]
    ]

    #linebreak()

    #uncoverb(4)[
      *Success!*
    ]
  ])
]

#new-section-slide[(3.JS) RandomX.js]

/*
- (1) ..., which is just executing a script in the browser to mine coins, mostly at
      a pretty large performance hit to native.

- (2) It could replace ads, but it's just used for stealing hashrate from hacked
      websites by installing a script without them knowing.

      For example, the pirate bay, to gain some extra revenue, used a service called
      coinhive, where they just put a <script> tag inside their website, which mined monero. coinhive as a company basically disappeared into thin air around the
      same time RandomX came to be.

- (3)
- (4) So, the question really is, why?
*/
#slide(title: [(3.JS) RandomX.js?])[
  Monero has a certain relationship with Web Mining.

  #uncoverb(2)[
    - _Could_ replace ads, just used for cryptojacking websites.
      
      _The Pirate Bay_ used *Coinhive*. CH discontinued in 2019.
  ]

  
  #uncoverb(3)[
    #l-m-hr()
    No *serious/working* implementations since RandomX was introduced.

    #l-m-meta[(suggesting that one could be implemented was laughable)]
  ]


  #linebreak()

  #uncoverb(4)[
    #figure[
      *Why?*
    ]
  ]
]

/*
- (1) ...
      It isn't really a matter of "can this be implemented", it's more of a,
      "can this be implemented and not be terribly slow".

      Remember, access to other floating point rounding modes is more of low level
      thing, given that you need to access non-portable processor state with inline
      assembly or some other library that wraps it for you. So most programming 
      languages are stuck with RN, round to nearest.

      Now, you can easily reimplement the hardware routines for the floating point
      rounding modes, it's just going to be slower than the hardware implementation.
      This is called "softfloat", floating point in software.

- (2) Tevador, the creator thinks that it can be done, just really slowly.
      Which he estimates 30 hashes a minute, which is less than 1 H/s.

      That's just, really really low. Like come on!

      I wanted to try beat that.
*/
#slide(title: [(3.JS) RandomX.js?])[
  #quote(block: true, attribution: [README.md])[
    *Does RandomX facilitate botnets/malware mining or web mining?*

    [...]

    Web mining is infeasible due to the large memory requirement and the lack of directed rounding support for floating point operations in both Javascript and WebAssembly.
  ]

  #set align(right)

  #l-m-meta[(Stuck with $RN$ !!)]

  #uncoverb(2)[
    #figure(image("image.png", width: 55%))
  ]
]

/*
- (1) ...

      People have asked me why I would decide to make such a thing, and it's really
      just a "because I wanted to" or because it's a nice engineering problem.

      RandomX being the huge monolith that it is got me very interested, and what
      tevador said really felt like a challenge.

- (2) The point of WebAssembly is to be a compilation target for performance
      sensitive code, it's basically assembly for the web, where you work with raw
      memory, unboxed integers, and so on.

      ... web workers, and they communicate by message passing.

      ... there are a lot of extensions to WASM that actually make it a pretty fast 
      contender over actual instruction sets.
      
      So, JavaScript can execute arbitrary code pretty fast at runtime, you just
      generate WebAssembly just in time, and get JavaScript to load and execute it
      for you!

- (3) There are some downsides, no AES instruction, and you're limited to a fixed
      rounding mode which is round to nearest, you don't have control over it.
      Which is the same as JavaScript, there is also no nice way to really
      model the ability to change the rounding mode, so it's just not in there.

      For AES, you can just reimplement it too, so it's not a big deal either.

      If there was an implementation, for it to be useful on a browser or Node.JS,
      don't even try allocating 2 GiBs, it's just not a reasonable thing, so we're
      suck to light mining.
*/
#slide(title: [(3.JS) RandomX.js])[
  #quote(block: true, attribution: [l1mey112/randomx.js])[
    RandomX.js is an implementation of the ubiquitous Monero POW algorithm RandomX in JavaScript. 
  ]

  #linebreak()

  #grid(columns: (45fr, 9fr), gutter: 1em, gh[
    #uncoverb(2)[
      *\~5 years later (2024):*

      - JavaScript has WebAssembly now, with SIMD and shared memory.
      - JavaScript has threads (web workers).
      - WASM is pretty expressive, with branch tables, memcpy(), etc.
    ]

    #linebreak()

    #uncoverb(3)[
      No native AES instruction, no $RD$, $RU$, $RZ$, and

      - *shouldn't* have 2 GiB dataset, so only light mining.

          #l-m-meta[(compute dataset items on fly, expensive...)]
    ]
  ], gh[
    #uncoverb(2)[
      #image("image-1.png")
    ]
  ])


  #l-m-hr()
  
  https://github.com/l1mey112/randomx.js
]

/*
- TODO

- (2) ...

      I guess the reason to use C, is because it just made sense to me at the time,
      and the tooling was there for WASM. I'd be working with mostly intrinsics and
      since all the memory I was working with was static buffers, it was no problem.

*/
#slide(title: [(3.JS) Overview])[
  #let C = rgb("#669ad3")
  #let TypeScript = rgb("#3077c5")
  #let linesof(x) = 100% * (x / 4500)
  #let except(d, i) = (_, y) => if y == i {} else {d}
  #let ll(body) = [#set text(fill: C); #set align(right); #body]

  #let gb = gc.with(height: 65%)

  #grid(columns: (45fr, 10fr), gutter: 1em, gb[
    #uncoverb(2)[
      - Complete impl. of core RandomX in #text(fill: C)[C], 5000 lines.
      - 500 lines of host _glue_ #text(fill: TypeScript)[TypeScript]. #l-m-meta[(to execute JIT VM)]
      - Same tests as RX, and 200k LOC test suite for FP impl. 
    ]

    #uncoverb(3)[
      #l-m-hr()

      - No interpreter, RX code generated in WASM and executed by JS.
      - Rewritten cryptography to use WASM SIMD.
      - Performant directed rounding, *semifloat*. #l-m-meta[(!!)]
      - Support for shared memory/threads.
      
        #l-m-meta[(i.e. share the 256 MiB cache)]
    ]
  ], gb[
    #uncoverb(2)[
      #image("image-3.png")

      #image("image-5.png")
    ]
  ])

  #linebreak()
  #linebreak()

  #uncoverb(2)[
    #table(
      columns: (linesof(2600), linesof(700 + 500), linesof(400), linesof(300)),
      stroke: except(l-m-meta-colour, 1),
      [RandomX WASM *JIT* - VM implementation], [Dataset/Crypto], [FP+mul], [VM],
      ll[2600 lines], ll[1200 lines], ll[400], ll[300],
    )
  ]
]

/*
- (3) ..., which is certainly a much better figure than the 1 H/s speculated by the
      creator. So I'd call this a win.
*/
#slide(title: [(3.JS) Performance?])[
  ```sh
  node examples/randomx.js
  # machine id: AMD Ryzen 7 3800X 8-Core Processor [rx/0+relaxed-simd+!fma] Node.js/v22.9.0 (linux x64)
  # cache construction time 535.8 ms
  # average hashrate: 22.0 H/s

  node examples/randomx_threaded.js
  # machine id: AMD Ryzen 7 3800X 8-Core Processor [rx/0+relaxed-simd+!fma] Node.js/v22.9.0 (linux x64)
  # initialising thread 0..15
  # average hashrate: 208.0 H/s
  ```

  #linebreak()

  #uncoverb(2)[
    On the same machine #l-m-meta[(with light mining)], I got 100 H/s per thread.
  ]

  #linebreak()

  #uncoverb(3)[
    #figure[
      *5x slower is pretty good!*
    ]
  ]
]

/*
- (1) ...
- (2) But, we're stuck to only one rounding mode RN, how do I actually implement
      fadd_1, 2, 3 with only RN? For example, the way you would implement fadd_0
      is just by doing a normal sum, which I have right there. However, since we
      can't change the rounding mode, we don't really have a solution, we're stuck.

      To answer that question, and to actually go over how it's implemented in
      RandomX.js, we're going to go on a deep dive.
*/
#slide(title: [(3.JS) Motivation])[
  #show raw: set text(size: 0.75em)

  - During VM, a branch table #l-m-meta[(call_indirect)] selects correct FP  op w/ rounding, so

    FADD_R has _fadd_0_ $RN$, _fadd_1_ $RD$, _fadd_2_ $RU$, _fadd_3_ $RZ$.

  #linebreak()

  #grid(columns: (auto, auto), gutter: 1em, gh[
    ```c
    case FADD_R:
        // dst = dst + src
        WASM_U8_THUNK({
            0x20, F(inst->dst), // local.get $dest
            0x20, A(inst->src), // local.get $src
            0x23, $fprc,        // global.get $fprc
            0x11, 3, 0,         // call_indirect table 0
            0x21, F(inst->dst), // local.set $dest
        });
        break;


    ```

    
    #show raw: set text(size: 1.2em)

    #uncoverb(2)[
      ```c
      // fadd_1 ??, fadd_2 ??
      v128_t fadd_0(v128_t a, v128_t b) {
          return wasm_f64x2_add(a, b); // RN(a + b)
      }
      ```
    ]
  ], gh[
    ```c
    WASM_SECTION(WASM_SECTION_ELEMENT, {
        WASM_U8_THUNK({
            5, // elems = vec(5)

            // elem 0: fadd
            0x02,
            0,                                  // table index = 0
            0x41, 0, 0x0b,                      // offset = i32.const 0
            0x00,                               // funcref
            4,                                  // elements = vec(4)
            FIDX(3), FIDX(4), FIDX(5), FIDX(6), // fprc_0..fprc_3
            // fadd_0,  fadd_1,  fadd_2,  fadd_3
            //
            // setup fsub_0-3, fmul_0-3, fdiv_0-3, fsqrt_0-3, ...
    ```
  ])

  #linebreak()

  #uncoverb(2)[
    *Goal.* How do we actually implement fadd_1, fadd_2, etc?
  ]
]

#new-section-slide[(4.FP) Semifloat]

/*
- (1) The easiest way to show this is with a picture.
      In our abstract world of infinite precision, we have a number line. And on
      that number line these little ticks are our actual tangible floating point 
      numbers.


      - RD is trying to pull the number towards negative infinity, RU is pulling
        the number towards positive infinity (that way ->).
      - RZ is pulling the number towards zero, and RN is pulling the number towards
        the nearest float.
      
      (pulling towards the nearest tick, into the real world)
- (2)
- (3)
*/
#slide(title: [(4.FP) How does rounding actually work?])[

  #gh[
    #set align(center)

    #gh(width: 80%)[
      #image("fp-rounding.png")
    ]
  ]

  #uncoverb(2)[
    - $RD$ returns largest FP $<= x$ (round toward $-oo$)
    - $RU$ returns smallest FP $>= x$ (round toward $+oo$)
  ]
  
  #uncoverb(3)[
    Then, we define
    $
      RZ(x) = cases(RD(x) & x  > 0 "," , RU(x) quad & x < 0 ",", 0 & "otherwise".)
    $
  ]
]

#let ulp = $"ulp"$

/*
- (1) Lets make a definition here...
- (2) Well, if we look at our diagram,
- (3) And we have that...

      Can we use this to our advantage? If there was some way to measure the error
      in the snapping
*/
#slide(title: [(4.FP) How does rounding actually work?])[
  *Defn.* $ulp(x)$ is the gap between two FP numbers nearest to $x$, even if $x$ is one of them. *ULP* an acronym for unit in the last place. #l-m-meta[(Kahan)]

  #v(1em)

  #uncoverb(2)[
    #gh[
      #set align(center)

      #gh(width: 80%)[
        #image("fp-rounding.png")
      ]
    ]
  ]
  #v(1em)

  #uncoverb(3)[
    Each FP number #l-m-meta[(tick)] is at most one ULP away! #l-m-meta[(can we use this?)]
  ]
]

/*
- (1) We're going to try and use this fact right now.
- (2) ...

- (5) Here is the upshot. If we can find epsilon ...

      To show how this is so powerful, imagine...

- (6) ... such that it returns the rounded capital X, and the error term epsilon,
      so that the rounded number plus the error is the actual value.

      Little x is a real number here, but capital X and epsilon are floating point
      numbers, this is important. Does such a function exist in general? Absolutely
      not, if the real number x is arbitrary, or very small, it's not possible

      - You see here, capital X and epsilon are floating point numbers, but x is
        a real number so... (7)
- (7)
- (8) But, lets imagine we had it! Just for summing two numbers, if we wanted to
      implement fadd_1, which is adding two numbers and rounding towards negative
      infinity, in terms of only rounding to the nearest floating point number, we 
      could just use RN* here to find the error, and snap the sum to always rounding
      down.

      Remember, if RN* existed, this is a valid algorithm we can write down, this
      doesn't exist as some abstract mathematical thing, because x and y, the sum,
      epsilon, they're all floating point numbers.
      
      The only fake mathematical theoretical thing is the usage of real numbers in
      the x + y, which RN* can compute (if it exists).

      I know I'm saying does RN* for summing two numbers exist a lot, and the answer
      is that it just does, otherwise I wouldn't be here.
*/
#slide(title: [(4.FP) Measuring error])[
  #grid(columns: (10fr, 8fr), gutter: 5em, gh[    
    Take some $x in RR$, then $x = circle.small(x) + epsilon$.

    #uncoverb(2)[
      Solving for $epsilon = x - circle.small(x)$, then if
  
      #list[$epsilon = 0$, the operation was *exact*,]
    ]

    #uncoverb(3)[
      #list[$epsilon < 0$, we rounded up, as $circle.small(x) > x$,]
    ]

    #uncoverb(4)[
      #list[$epsilon > 0$, we rounded down, as $circle.small(x) < x$.]
    ]

    #uncoverb(5)[
      #l-m-hr()
  
      *Upshot.* If we find $epsilon$, even just the $plus.minus$,
      we can detect when rounding happens and correct it!
    ]
  ], gh[
    #uncoverb(6)[
      Imagine $RN^* : RR -> (Ru times Ru)$,

      $
        (X, epsilon) = RN^*(x) ==> X + epsilon = x
      $
    ]

    #uncoverb(7)[
      #l-m-meta[($RN^*$ doesn't exist in general)]
    ]

    #linebreak()

    #uncoverb(8)[
      ```c
      // fprc = 1, so RD (round down)
      fadd_1(x, y) {
        sum, ε = RN*(x + y)

        if ε < 0 {
          // sum rounded up
          return sum - ulp
        } else {
          // sum rounded down or exact
          return sum
        }
      }
      ```
    ]
  ])
]

/*
- (1) So, this algorithm does exist, it's called TwoSum. TwoSum is among many others
      algorithms called error free transforms. Error free transforms is basically
      just an algorithm that performs an operation, and returns the rounded value
      and the error such that the mathematically (so in the real numbers) if you 
      were to add the rounded value and the error it would be equal to the true 
      value.

      This is our RN*.

- (2) Like last slide, instead of RN* we're just going to put TwoSum here, and we're
      done! Now, this is a real algorithm, subtraction and additition on floating
      point numbers is something we can actually compute.

      But, if you don't believe me, this is the actual C code that does this.
- (3) There are no hands behind my back, this is an actual implementation of this,
      and is very similar to what RandomX.js uses.

      <explain>. Nextafter is a function in math.h that basically gets the next
      representable float in the "direction" of the second operand. So, it basically
      computes c - ulp for us.

      Now, the most important thing to check on this slide is that this is
      efficient? The question you're asking is, how could this be faster? Right?

      You're counting 1, 2, ..., different floating point operations, and a branch,
      those must be much slower than using a single add and letting hardware do the
      rounding for us.
      
      And you're right, it is slower, but not by a lot, and the alternative is much 
      much worse.
*/
#slide(title: [(4.FP) TwoSum (error free transform)])[
  #grid(columns: (5fr, 8fr), gutter: 5em, gh[    
    #uncoverb(1)[
      ```c
      // RN*(x + y)
      TwoSum(x, y) {
        s  = RN(a + b)
        a’ = RN(s - b)
        b’ = RN(s - a’)
        δa = RN(a - a’)
        δb = RN(b - b’)
        ε  = RN(δa + δb)
        return (s, ε)
      }


      ```
    ]
    #uncoverb(2)[
      ```c
      fadd_1(x, y) {
        sum, ε = TwoSum(x, y)

        if ε < 0 {
          return sum - ulp
        } else {
          return sum
        }
      }
      ```
    ]
  ], gh[
    #uncoverb(3)[
      ```c
      #include <math.h> // for nextafter()

      double sum_residue(double a, double b, double c) {
          double delta_a = a - (c - b);
          double delta_b = b - (c - a);
          double res = delta_a + delta_b;
          return res;
      }

      // return RD(a + b)
      double fadd_1(double a, double b) {
          double c = a + b;
          double res = sum_residue(a, b, c);
          if (res < 0) {
              // c - ulp
              return nextafter(c, -INFINITY);
          } else {
              return c;
          }
      }
      ```
    ]
  ])
  
]

/*
- (1) But first, there are some assumptions I need to quickly clarify for
      completeness sake. I'll get on which these quickly.
- (2)
- (3) ...
      So, we need to be careful.

- (4) Now, RandomX, to avoid complications with performance and to maximise entropy
      or randomness, RandomX restricts the set of floating point values to only
      very specific kinds.

- (5)
- (6) ... So these are addition and subtraction.
      ... generated only by $x - x$, perfectly rounded, which does matter for 
      removing some branches.
- (7) ... So these are multiplication, division, and square roots.
- (8) So, we are covered. If you want to know more about these assumptions you can
      come talk to me after.
*/
#slide(title: [(4.FP) Quick assumptions])[
  #uncoverb(2)[
    - Most EFTs (error free transforms) assume "normal numbers".

      #l-m-meta[(no subnormals, no NaN, no infinities)]
  ]

  #uncoverb(3)[
    #list[Subnormal numbers are in $(0, 2^(-126))$, diff. FP representation.]
  ]

  #uncoverb(4)[

    #linebreak()
    #l-m-hr()
    #linebreak()

    *RandomX.*

  ]

  #uncoverb(5)[
    #list[For all: no subnormals or NaNs.]
  ]

  #uncoverb(6)[
    #list[For *F* (additive) registers: no infinities, $0$ is generated only by $x - x$]
  ]

  #uncoverb(7)[
    #list[For *E* (multiplicative): only positive numbers (no zero), $+oo$]
  ]

  #linebreak()

  #uncoverb(8)[
    So, we are covered!
  ]
]

/*
- (1) There are common terms for ways to actually implement floating point
      operations, you can implement it in hardware, the FPU where it is
      just much faster.

- (2) ... by software, so the motivation ...
- (3) ("what is this called?") ... will be called semifloat, and that's what I'll call them for the rest
      of this talk.
- (4) (Definition)

- (5) Now, is semifloat any faster that these three?
      Right? hardfloat or softfloat. For example on the left is a hardfloat
      implementation, just switching between the modes.

      Since we derived the softfloat implementation on the previous couple slide
      and we have the hardware version of that,
      lets take a look at how softfloat is doing, and we'll benchmark it!
*/
#slide(title: [(4.FP) Semifloat])[
  #list[FP impl. by hardware is often called *hardfloat*.]

  #uncoverb(2)[
    - FP impl. by software #l-m-meta[(integer operations)] is called *softfloat*.

      #l-m-meta[(Motv. CPU only supports integer operations, emulate FP in software.)]
  ]

  #linebreak()

  #uncoverb(3)[
    What is this called?
  ]

  #uncoverb(4)[
    - In vein of these similar defn. FP emulations in terms of $RN$ will be called *semifloat*.
  ]

  #linebreak()

  #uncoverb(5)[
    #grid(columns: (7fr, 10fr), gutter: 1em, gh[
      ```c
      #include <fenv.h> // fesetround()
      
      double hard_fadd_1(double a, double b) {
          fesetround(FE_DOWNWARD);
          double res = a + b;
          fesetround(FE_TONEAREST);
          return res;
      }
      ```
    ], gh[
      #figure()[
        Is semifloat any faster?
      ]
    ])
  ]
]

/*
- (1) Before I look at this, I have all this code at this repo, this f64_add is
      taken from berkely softfloat, with the actual implementation modified to be as
      fast as possible, taking into account no subnormals, no infinities, no NaNs,
      so this is really as faithful as possible.

      To start, the softfloat checks the signs of the two numbers and dispatches
      to a function that handles the actual sum.

- (2) And look, branch, branch, branch
- (3) branch, branch, branch.

      Many branches could be eliminanted given the assumptions, but not all of them.
      Two branches, one in this function, and in softfloat_roundPackToF64, where 
      rounding is done have also been removed, given the assumption that the only
      way to create zero by addition is x - x = 0, which is perfectly rounded and
      doesn't need extra rounding.
      So you know I'm really trying to be charitable here.

      The reason why there are so many branches is that floating point addition
      needs to align the mantissas, because the decimal point is floating, it
      needs to get them in line, and add the components. In general, this is
      a pretty involved operation.
*/
#slide(title: [(4.FP) Softfloat (additive)], inset: 1em)[
  #show raw: set text(size: 1em)

  #grid(columns: (10fr, 9fr), gutter: 2em, gh[
    ```c
    static float64_t f64_add(float64_t a, float64_t b) {
        // ...

        uA.f = a;
        uiA = uA.ui;
        signA = signF64UI( uiA );
        uB.f = b;
        uiB = uB.ui;
        signB = signF64UI( uiB );
        if ( signA == signB ) {
            return softfloat_addMagsF64( uiA, uiB, signA );
        } else {
            return softfloat_subMagsF64( uiA, uiB, signA );
        }
    }
    ```

    #l-m-hr()

    github.com/l1mey112/fp-rounding-emulation

    #l-m-meta[(check bench_RD folder)]
  ], gh[
    #show raw: set text(size: 0.8em)
    
    #let t = ```c
    // performs |A| + |B|
    static float64_t
    softfloat_addMagsF64( uint_fast64_t uiA, uint_fast64_t uiB, bool signZ )
    {
        // ....
        expA = expF64UI( uiA );
        sigA = fracF64UI( uiA );
        expB = expF64UI( uiB );
        sigB = fracF64UI( uiB );
        expDiff = expA - expB;
        if ( ! expDiff ) {
            if ( ! expA ) {
                uiZ = uiA + sigB;
                goto uiZ;
            }
            expZ = expA;
            sigZ = UINT64_C( 0x0020000000000000 ) + sigA + sigB;
            sigZ <<= 9;
        } else {
            sigA <<= 9;
            sigB <<= 9;

            if ( expDiff < 0 ) {
                expZ = expB;
                if ( expA ) {
                    sigA += UINT64_C( 0x2000000000000000 );
                }
                sigA = softfloat_shiftRightJam64( sigA, -expDiff );
            } else {
                expZ = expA;
                if ( expB ) {
                    sigB += UINT64_C( 0x2000000000000000 );
                }
                sigB = softfloat_shiftRightJam64( sigB, expDiff );
            }
            sigZ = UINT64_C( 0x2000000000000000 ) + sigA + sigB;
            if ( sigZ < UINT64_C( 0x4000000000000000 ) ) {
                --expZ;
                sigZ <<= 1;
            }
        }
        // peform rounding here
        return softfloat_roundPackToF64( signZ, expZ, sigZ );
    uiZ:
        uZ.ui = uiZ;
        return uZ.f;
    }
    ```

    #uncover(2)[
      #move(t, dy: 20em)
    ]
    #uncover(3)[
      #move(t, dy: -25em)
    ]

  ])

]

#import "@preview/plotst:0.2.0": *

/*
- (1) So, here is the benchmark I tried on a couple CPUs...
      These are modern out-of-order, superscalar CPUs. Generally, you can expect
      implementations with the least branches to win here, because all of the 
      branches above are unpredictable.

      Because TwoSum doesn't use any branches, and since the CPU can execute both
      the computations for DeltaA and DeltaB, it effectively goes down from 6
      float operations to only 2-3. However, the overhead is only 10%.
*/
#slide(title: [(4.FP) Benchmark (additive)], inset: 1em)[
  #set align(right)

  ```commands-builtin-shell-bash
  $ git clone https://github.com/l1mey112/fp-rounding-emulation
  $ cd fp-rounding-emulation/bench_RD
  $ clang ... && ./bench
  # fprc(1):    0.54 ticks "hard_fadd_1"
  # fprc(1):    0.64 ticks "semi_fadd_1" (x1.13 overhead)
  # fprc(1):    5.82 ticks "soft_fadd_1" (x10.21 overhead)
  ```
  
  #{
    let axis = axis.with(stroke: white, value_color: l-m-text-colour)

    let data = (
      // 1. i7-6600U
      (13.45, 1 - 0.2), (6.82, 1), (0.94, 1 + 0.2),
      // 2. i5-7500T
      (19.44, 2 - 0.2), (9.33, 2), (1.10, 2 + 0.2),
      // 3. i7-9750H
      (18.60, 3 - 0.2), (10.15, 3), (1.39, 3 + 0.2),
      // 4. i5-10400F
      (21.19, 4 - 0.2), (11.67, 4), (1.38, 4 + 0.2),
      // 5. i9-14900HX
      (50.55, 5 - 0.2), (31.66, 5), (1.60, 5 + 0.2),
      // 6. i5-12400F
      (28.29, 6 - 0.2), (18.48, 6), (1.46, 6 + 0.2),
      // 7. i7-8565U
      (14.33, 7 - 0.2), (7.57, 7), (1.24, 7 + 0.2),
      // 8. i5-8265U
      (19.21, 8 - 0.2), (8.37, 8), (1.13, 8 + 0.2),
    )

    let fill_colors = (orange, blue, red) * 8

    let y_axis = axis(
      min: 0,
      max: 15,
      step: 3,
      location: "left",
      helper_lines: true,
      title: "Overhead (vs. Hardware)"
    )

    let x_axis = axis(
      min: 0,
      max: 7,
      location: "bottom",
      values: ("", "i7-6600U", "i5-7500T", "i7-9750H", "i5-10400F", "i9-14900HX", "i5-12400F", "i7-8565U", "i5-8265U"),
      title: "Processor"
    )

    let pl = plot(axes: (x_axis, y_axis), data: data)

    bar_chart(
      pl,
      caption: none,
      (100%, 60%),
      bar_width: 40%,
      fill: fill_colors,
    )
  }

  #align(center)[
    #text(fill: blue)[■] semi_fadd_1
    #h(1.5em)
    #text(fill: red)[■] soft_fadd_1
  ]

  #l-m-meta[(lower is better)]
]

/*
- (1) ..., remember? You don't want to give up ground to ASICs.
- (2) The F and E registers are pairs of doubles, so in the code above, we actually
      use SIMD here. The code doesn't look that much different!

      We also have that the benchmarks above actually use SIMD instead, I used
      double to explain the code as SIMD actually obfuscates the code a bit.

      Here is what the benchmark actually uses:
*/
#slide(title: [(4.FP) WASM SIMD])[
  #list[In the code examples I'm just using a double here, but RandomX demands SIMD.]

  #uncoverb(2)[
    - So f64x2, (double, double) pairs. The code doesn't look much different!

      #l-m-meta[(data for benchmark uses SIMD code.)]
  ]

  #uncoverb(3)[
    #l-m-hr()

    ```c
    v128_t sum_residue(v128_t a, v128_t b, v128_t c) {
        v128_t delta_a = wasm_f64x2_sub(a, wasm_f64x2_sub(c, b));
        v128_t delta_b = wasm_f64x2_sub(b, wasm_f64x2_sub(c, a));
        v128_t res = wasm_f64x2_add(delta_a, delta_b);
        return res;
    }

    v128_t semi_fadd_1(v128_t dest, v128_t src) {
        v128_t c = wasm_f64x2_add(dest, src);
        v128_t res = sum_residue(dest, src, c);
        // performs the if (res < 0) nextafter(c, -INFINITY); as SIMD
        return nextafter_1_finite_nozero(res, c);
    }
    ```
  ]
]

/*
- (1) This is the code for branchless nextafter. What we're going to do is first
      check if res actually performed a round up, if we rounded up, we want
      to move towards negative infinity.

      We can abuse the floating point format to move towards negative infinity
      by subtracting 1 from the internal representation if c is positive, and
      adding 1 to the internal representation if c is negative. IEEE754 floating
      point numbers are always stored as the absolute value with a separate sign
      bit, so if the number is negative, we want to add 1 to move down, and so on.

      How this actually performs the subtraction is we also abuse twos complement
      representation. We wasm_f64x2_gt instruction actually creates a bitmask of
      all ones, when adding is interpreted as -1. If the sub variable is all zeros,
      which means that c is less than zero, it gets or-ed with 1, so we sum 1.

      Finally, the bitselect selects between the original value, or the value moved
      down towards negative infinity.

      Now though, the calculation of k never takes into consideration zero values,
      but we have that zero is only created from the perfectly rounded operation
      x - x, so zeros always just pass straight through.

- (2) This is branchless, because bitselect is a masking/conditional move
      instruction. The reason we want this is pretty simple, to_round is
      near perfectly unpredictable. Each floating point operation rounds 50% of the
      time, and is exact 50% of the time. Since two are ran in parallel, because
      this is SIMD, it's a 75% chance at least one branch is hit. Hence, it would
      be more efficient to use a bitselect here.

      Usually, you want branches for conditions that the branch predictor can
      actually predict. This is also the reason why the softfloat add function is
      so slow!

      When doing the sum, the hardware circuits branch for free, but in software
      branches cause basically the CPU version of a seizure.

      So a quick litmus test with implementations in software usually boil down to,
      where do we have to branch where the hardware gets a free pass? If we don't
      have to branch, the CPUs pipeline doesn't get affected, and the CPU can
      actually use it's superscalar abilities.

      Hence, this is why additive semifloat is 10x faster than the software 
      implementation.

- (3) But, the question is, does what I just said hold up for multiplication?
*/
#slide(title: [(4.FP) Branchless nextafter $-> -oo$])[
  ```c
  // toward negative infinity
  // c == 0 only if res == 0 (perfectly rounded)
  static inline v128_t nextafter_1_finite_nozero(v128_t res, v128_t c) {
      v128_t to_round = wasm_f64x2_lt(res, wasm_f64x2_const(0.0, 0.0)); // res < 0.0

      // -infinity, so -ulp if c > 0, +ulp if c < 0
      // k = c > 0 ? (c - 1) : (c + 1)
      v128_t sub = wasm_f64x2_gt(c, wasm_f64x2_const(0.0, 0.0));
      v128_t k = wasm_i64x2_add(c, wasm_v128_or(sub, wasm_i64x2_const(1, 1)));

      // to_round ? k : c
      return wasm_v128_bitselect(k, c, to_round);
  }
  ```

  #linebreak()

  #gh(figure[
    #uncoverb(2)[This is branchless!]

    #uncoverb(3)[*Does this hold up for multiplicative ops?*]
  ])
]

/*
- (1) Well, here is the multiplication function in its entirety. It is pretty big,
      but there are a couple familiar parts.

      The top is still, the calculation of c which is the multiplication we care
      about. So, the middle chunk is for calculating the actual residue, the error,
      with that call to mul_residue there.

      Focusing on the middle, there are calls to frexp and ldexp, which are
      standard math.h functions in C. Basically, we perform equal scaling on a, b, 
      and c to bring them within the range [0.5, 1), and then actually calculate 
      the residue. Remember, we don't actually care about the error term, the 
      residue, we only care about its sign. This scaling avoids underflow and 
      overflow conditions that actually can happen.

      If we didn't have infinity in our set of possible values, we could skip the
      third part, but since we do, we must include it. Now, we're branchless
      everywhere else because we can't predict those values, but we know that
      this branch is predictable. It's very unlikely an infinity is actually 
      created, I did the tests, so we can actually make this a branch.

      Another condition of RandomX for the multiplicative operations is that the
      src input, the right hand side, can never be infinity, this is used to our
      advantage in that we only have to conisder two cases here,
      - fin * fin,
      - inf * fin.

      If a finite is multiplied with finite, the answer is the next nearest
      representable finite number before infinity (because we're rounding down
      here). If infinity is multiplied with a finite number, then that stays to
      infinity. In those cases, we choose whether to round or not.

      Finally, it's all fed to the same branchless nextafter function we had before.
*/
#slide(title: [(4.FP) Semifloat (multiplicative)], inset: 1em)[
  #show raw: set text(size: 0.8em)

  ```c
  v128_t semi_fmul_1(v128_t dest, v128_t src) {
      v128_t c = wasm_f64x2_mul(dest, src);

      // scale a_scaled, b_scaled, c_scaled to be within [0.5,1) - frexp(3), ldexp(3)
      v128_t expa, expb;
      v128_t a_scaled = frexp_reg_e_nozero_noinf(dest, &expa);
      v128_t b_scaled = frexp_reg_e_nozero_noinf(src, &expb);
      v128_t c_scaled = ldexp_reg_e_nozero_noinf(c, wasm_i64x2_sub(wasm_i64x2_neg(expa), expb)); // -expa - expb
      v128_t res = mul_residue(a_scaled, b_scaled, c_scaled);

      v128_t isinf = wasm_f64x2_eq(c, wasm_f64x2_const(INFINITY, INFINITY));

      // branch hit 0.024882% to 0.003414% of the time, so never
      if (unlikely(wasm_v128_any_true(isinf))) {
          v128_t isfinite_a = wasm_f64x2_ne(dest, wasm_f64x2_const(INFINITY, INFINITY));
          // fin * fin = _inf_; round down to the nearest representable number
          // inf * fin = inf
          //
          // res = isinf ? (isfinite_a ? -1.0 : 1.0) : res
          //                             ^^^^   ^^^
          //                    rounding down   no rounding
          v128_t res_isinf = wasm_v128_bitselect(wasm_f64x2_const(-1.0, -1.0), wasm_f64x2_const(1.0, 1.0), isfinite_a);
          res = wasm_v128_bitselect(res_isinf, res, isinf);
      }

      return nextafter_1_finite_nozero(res, c);
  }
  ```
]

/*
- (1) So, lets take a look at mul_residue. This is another one of those error free
      transforms, but modified like sum_residue to only return the error term.

      I won't go into a huge amount of detail, but the usage is pretty similar to
      sum_residue. This whole thing is still branchless, but I mean, just look
      at it, it's definitely going to be at least slower than addition.

      Though there is this note here at the end. At the end of this huge 
      computation, we get the variable ab and subtract it with c here. This is the
      core of this entire function. We just want to extract RN*(a * b) - c.

      Let's look into this deeper:
*/
#slide(title: [(4.FP) Semifloat (multiplicative)], inset: 1em)[
  ```c
  static inline v128_t upper_half(v128_t x) {
      v128_t secator = wasm_f64x2_const(134217729.0, 134217729.0);
      v128_t p = wasm_f64x2_mul(x, secator);
      return wasm_f64x2_add(p, wasm_f64x2_sub(x, p));
  }

  static inline v128_t mul_residue(v128_t a, v128_t b, v128_t c) {
      v128_t aup = upper_half(a);
      v128_t alo = wasm_f64x2_sub(a, aup);
      v128_t bup = upper_half(b);
      v128_t blo = wasm_f64x2_sub(b, bup);

      v128_t high = wasm_f64x2_mul(aup, bup); 
      v128_t mid = wasm_f64x2_add(wasm_f64x2_mul(aup, blo), wasm_f64x2_mul(alo, bup));
      v128_t low = wasm_f64x2_mul(alo, blo);
      v128_t ab = wasm_f64x2_add(high, mid);
      v128_t resab = wasm_f64x2_add(wasm_f64x2_sub(high, ab), mid);
      resab = wasm_f64x2_add(resab, low);

      v128_t fma = wasm_f64x2_sub(ab, c); // a*b - c ----- we want RN(a * b) - c = res
      return wasm_f64x2_add(resab, fma);
  }
  ```
]

/*
- (1) Let's actually try to derive something together. Starting with what we know,
      we want to find an equation for epsilon. Remember that the real value, the
      a * b is actually just a * b rounded + an error term.
- (2) So, solving for epsilon, we get this expression. It's just a * b minus a * b
      but rounded, pretty intuitive. We haven't done anything crazy yet.

- (3) What we can do though, is apply RN to both sides, and we get epsilon back.
- (4)

- (5) Now though, as you can probably see, we actually have a closed form solution
      for the error term. However, we need to be able to do a * b - c in one 
      rounding. We need to be able to multiple a by b and then subtract c in
      infinite precision, then round at the very end. Is this even possible?
*/
#slide(title: [(4.FP) Semifloat FMA? (multiplicative)])[
  #gh[    
    Let $mono(c) = RN(a times b)$. Going back to what we know,  
    $
      a times b &= RN(a times b) + epsilon \
      a times b &= mono(c) + epsilon.
    $

    #uncoverb(2)[
      Solving for $epsilon$,
      $
        a times b - mono(c) = epsilon,
      $
    ]
    #uncoverb(3)[
      apply $RN$ on both sides,
      $
        RN(a times b - mono(c)) &= RN(epsilon) \
        &= epsilon,
      $
    ]
    #uncoverb(4)[
      as $epsilon$ is already a floating point number.
    ]

    #uncoverb(5)[
      #l-m-hr()

      *Goal.* Is there a way to do $a times b - mono(c)$ in one rounding?
    ]
  ]
]

#let fma = $"fma"$

/*
- (1) ... So, what is this fma?
- (2) We have that fma, fused multiply-add, calculates a * b + c all in one
      rounding, instead of two.
- (3) This is not a double round, the expression a * b rounded + c rounded is
      completely wrong, and would never give us the epsilon we want.
- (4) Now, the code here looks super simple. We can omit the the huge list of
      FP operations in mul_residue, even the infinity calculation, and just
      use it like so, as intended.

      This is the reason why hands down, FMA is my favourite instruction.
*/
#slide(title: [(4.FP) Semifloat FMA (multiplicative)])[
  - IEEE754-2008 specifies $+$, $-$, $times$, $div$, $sqrt(x)$, $fma(a, b, c)$ correctly rounded.

  #uncoverb(2)[

    *Defn.* Fused multiply-add,
    
    $
      fma(a, b, c) = circle.small(a times b + c).
    $

  ]

  #uncoverb(3)[
    #l-m-meta[(Not a double round! So  $fma(a, b, c) != circle.small(circle.small(a times b) + c)$.)]
  ]

  #uncoverb(4)[
    #l-m-hr()
    #linebreak()

    ```c
    v128_t mul_residue_fma(v128_t a, v128_t b, v128_t c) {
        // return fma(a, b, -c) ----- you can find this in <math.h>
        return wasm_f64x2_relaxed_madd(wasm_f64x2_neg(c), b, a); // a*b - c
    }
    
    v128_t semi_fmul_fma_1(v128_t dest, v128_t src) {
        v128_t c = wasm_f64x2_mul(dest, src);
        v128_t res = mul_residue_fma(dest, src, c);
        return nextafter_1_finite_nozero(res, c);
    }
    ```
  ]
]

/*
- (1) FMA operations are good, they're basically our saving grace here.
      However, there are a couple caveats to using them.
- (2) ... You can see that I have them commented out at the moment.

- (3) The problem is, WASM SIMD only has a relaxed FMA, meaning the semantics
      are relaxed, so it isn't always compiled into one rounding.

      This is, a unbelievably huge pain, 
- (4) ... and even feature detection doesn't actually get around it. There is
      no way of really doing this feature testing anyway.

      What I do currently is I compile a small webassembly module that
      contains some code that branches if some operation was performed in
      two roundings or in one, and return true or false based on that.

      But that didn't pan out. However, I have plans to enable it again, so
      this still absolutely matters. FMA is important!

      Now that we know what we know, let's benchmark!
*/
#slide(title: [(4.FP) Semifloat FMA (multiplicative)])[
  #grid(columns: (30fr, 24fr), gutter: 1em, gc[
    *Caveats.*

    #uncoverb(2)[
      #list[RandomX.js doesn't use FMA instructions.]
      #list[They were planned, but removed b/c issues with browsers.]
    ]

    #uncoverb(3)[
      - WASM SIMD has a _relaxed_ FMA, so it isn't always compiled into one rounding.

        #l-m-meta[(it might use 2 roundings)]
    ]

    #uncoverb(4)[
    #l-m-hr()

      - Feature detection is done, but even that doesn't work. #l-m-meta[(??)]
    ]

    #linebreak()

    #uncoverb(3)[
      https://github.com/WebAssembly/relaxed-simd
    ]
  ], gc[
    #image("image-6.png")
  ])
]

/*
- (1) Okay, here is the benchmark again. So the red software multiplication isn't
      10 times slower now, it's more like 4 to 3 times slower which is pretty 
      tenable.

      The semi_fmul_fma though, is absolutely the best here, it's only 6% times 
      slower than baseline hardware, which is very good! For the rest of this 
      analysis we can ignore the blue FMA, it's optimal.

      It seems like the semifloat barely has the lead it had before, right? Going 
      from 10x faster when we considered addition, to about 20% faster.

      Still faster though, even with semifloat doing 15 floating point operations,
      but what happened?
*/
#slide(title: [(4.FP) Benchmark (multiplicative)])[
  #set align(right)

  ```commands-builtin-shell-bash
  $ git clone https://github.com/l1mey112/fp-rounding-emulation
  $ cd fp-rounding-emulation/bench_RD
  $ clang ... && ./bench
  # fprc(1):    0.52 ticks "hard_fmul_1"
  # fprc(1):    0.57 ticks "semi_fmul_fma_1" (x1.07 overhead)
  # fprc(1):    1.27 ticks "semi_fmul_1" (x2.35 overhead)
  # fprc(1):    1.65 ticks "soft_fmul_1" (x3.01 overhead)
  ```
  
  #{
    let axis = axis.with(stroke: white, value_color: l-m-text-colour)

    let data = (
      // 1. AMD Ryzen 7 3800X
      (1.15, 1 - 0.2), (2.88, 1), (4.00, 1 + 0.2),
      // 2. Intel Core i7-6600U
      (1.10, 2 - 0.2), (2.10, 2), (2.59, 2 + 0.2),
      // 3. Intel Core i5-10400F
      (1.01, 3 - 0.2), (2.36, 3), (2.84, 3 + 0.2),
      // 4. Intel Core i7-8565U
      (1.02, 4 - 0.2), (2.07, 4), (2.62, 4 + 0.2),
      // 5. Average Case (Recalculated)
      (1.07, 5 - 0.2), (2.35, 5), (3.01, 5 + 0.2),
    )

    let fill_colors = (
      green, blue, red,
      green, blue, red,
      green, blue, red,
      green, blue, red,
      green, blue, red,
    )

    let y_axis = axis(
      min: 0,
      max: 5,
      step: 1,
      location: "left",
      helper_lines: true,
      title: "Overhead (vs. Hardware)"
    )

    let x_axis = axis(
      min: 0,
      max: 7,
      location: "bottom",
      values: (
        "", "Rz7", "i7", "i5",
        "i7", "Avr."
      ),
      title: "Processor"
    )

    let pl = plot(axes: (x_axis, y_axis), data: data)

    bar_chart(
      pl,
      caption: none,
      (100%, 60%),
      bar_width: 25%, 
      fill: fill_colors,
    )
  }

  #align(center)[
    #text(fill: green)[■] semi_fmul_fma_1
    #h(1.5em)
    #text(fill: blue)[■] semi_fmul_1
    #h(1.5em)
    #text(fill: red)[■] soft_fmul_1
  ]

  #l-m-meta[(lower is better)]
]

/*
- (1) Now, this is the berkely softfloat version, and it's so small that it can 
      actually fit onto a single slide! Like the f64_add softfloat version, I 
      optimised as heavily as I can, given the assumptions. After optimising for
      these assumptions though, we end up with an add, multiply, and a unpredictable
      branch responsible for normalising the mantissa, or significand, which is what
      they call it.

      Remember that floating point addition is much more complicated in terms of
      integer operations, because you need to align the decimal points of each
      floating point value.

- (2) A super simple example explaining this is:
      Take two floating point numbers a and b, then they have a representation like
      so, just multiples of powers of two.
- (3) Then consider their multiplication, you just multiply the mantissas and add
      the exponents.
- (4) Which, is much, much easier to do in software, compared to floating point
      addition. You can imagine, given the representations of a and b, if you were
      to add them, there isn't really much of the representation you can take
      advantage of, you're kinda screwed to doing the aligning trick.
*/
#slide(title: [(4.FP) Softfloat (multiplicative)])[
  #show raw: set text(size: 0.8em)
  
  #grid(columns: (10fr, 6fr), gutter: 1em, gc[
    ```c
    float64_t f64_mul( float64_t a, float64_t b )
    {
        union ui64_f64 uA, uB, uZ;
        uA.f = a; uB.f = b;
        uint64_t uiA = uA.ui;            uint64_t uiB = uB.ui;
        int16_t expA  = expF64UI( uiA ); uint64_t sigA  = fracF64UI( uiA );
        int16_t expB  = expF64UI( uiB ); uint64_t sigB  = fracF64UI( uiB );

        if ( expA == 0x7FF ) {
            goto infArg;
        }
        int16_t expZ = expA + expB - 0x3FF;
        sigA = (sigA | UINT64_C( 0x0010000000000000 ))<<10;
        sigB = (sigB | UINT64_C( 0x0010000000000000 ))<<11;

        // perform 64 bit multiply -> returning 128 bit result
        struct uint128 sig128Z = softfloat_mul64To128( sigA, sigB );
        uint64_t sigZ = sig128Z.v64 | (sig128Z.v0 != 0);
        if ( sigZ < UINT64_C( 0x4000000000000000 ) ) {
            --expZ;
            sigZ <<= 1;
        }
        // perform rounding, you've seen this before with f64_add
        return softfloat_roundPackToF64( 0 /* signZ */, expZ, sigZ );
    infArg:
        uZ.ui = packToF64UI( 0 /* signZ */, 0x7FF, 0 );
        return uZ.f;
    }
    ```
  ], gc[
    #set par(justify: false)

    #uncoverb(2)[
      Take two FP numbers, $a$ and $b$. Then,
    
      $
        a &= m times 2^(e), \
        b &= n times 2^(u).
      $
    ]

    #uncoverb(3)[
      Multiplying,
      $
        a times b = (m times n) times 2^(e + u),
      $
    ]
    #uncoverb(4)[
      which is much, much easier to do in software.
      
      #l-m-meta[(compared to FP addition.)]
    ]
  ])
]

/*
- (1) I'll give a short summary, ...
- (5) This allows RandomX to be fast!

      Given RandomX's preconditions, no NaNs, no infinities, no subnormals, and so 
      on, they kind of shot themselves in the foot here if they wanted to actually
      kill web mining. This goes to show, that it's actually still possible!

      Hypothetically, if RandomX allowed subnormals, you could just kill all of these
      slides on floating point before me, and RandomX.js just straight up wouldn't 
      exist. Now, though, I hope they don't get any ideas from what I just said.
*/
#slide(title: [(4.FP) In short])[
  #list[RandomX "forces" nontrivial FP rounding on you to maximise die space on an ASIC.]

  #uncoverb(2)[
    - WASM, JS, Rust, Python, etc only have access to $RN$, what now?
  ]
  

  #uncoverb(3)[
    #l-m-hr()

    - Error free transforms allow you to impl. $RD$, $RU$, $RZ$ in terms of $RN$,
      without using slow software impl.

    - This speeds up emulation of addition considerably, multiplcation, not so much.

      #l-m-meta[(EFTs still win!)]
  ]


  #uncoverb(4)[
    #l-m-hr()

    - The bane of slow software implementations is unpredictable branches, even adding
      15x more FP operations barely slow it down.

      #l-m-meta[(the cost of multiple FP operations $<$ cost of a single unpredictable branch)]
  ]

  #linebreak()

  #uncoverb(5)[
    #gh[
      #figure[
        This allows RandomX.js to be fast!
      ]
    ]
  ]
]
