#import "polylux/polylux.typ": *
#import "polylux/l-m.dev.typ": *

#set raw(tab-size: 4)
#show: metropolis-theme.with()
#set par(justify: true)

#let l-m-todo(body) = [#text(fill: l-m-meta-colour)[\/\/ ]#text(fill: l-m-accent-colour)[TODO: ] #text(fill: l-m-meta-colour, body)]
#let l-m-tldr(body) = [#text(fill: l-m-meta-colour)[\/\/ ]#text(fill: l-m-accent-colour)[tldr: ] #text(fill: l-m-meta-colour, body)]
#let span-sep(left, right) = box[#left #box(width: 1fr, repeat[#text(fill: l-m-meta-colour)[-]]) #right]

#show math.equation: set text(1.2em)

#let l-m-meta(body) = text(fill: l-m-meta-colour, body)
#let l-m-code(body) = text(fill: l-m-code-colour, body)

#let uncoverb(b, body) = uncover((beginning: b), body)

#let gc = block.with(
  width: 100%,
  height: 100%,
)

#let gh = block.with(
  width: 100%,
)

#title-slide({
  l-m-title("Zero to RandomX.js")
  linebreak()
  l-m-title("")
  l-m-hr()
  set text(size: 0.8em)
  text(fill: l-m-meta-colour, "Tuesday, October 3rd | Lecture Theatre 123 | 6 PM - 8 PM")
})

#slide(title: "About me")[
  - Liam, l-m, #underline[l-m.dev], #underline[l-m\@l-m.dev]
]

#focus-slide()[
  Let Me Paint A Picture. TODO change this
]

/*
*/
#slide(title: "What is Monero?")[
  - Introduce
]


/* TODO: Required knowledge
    - Hashes
*/
#new-section-slide[(1.POW) Proof-of-Work Consensus]

#new-section-slide[(2.RX) RandomX]

/*
- (3) By then, ASICs for cryptonight have already been created, so the switch was needed.
*/
#slide(title: [(2.RX) RandomX])[

  RandomX is a proof-of-work algorithm that is optimized for general-purpose CPUs. It has stood the test of time as an *ASIC resistant* hash function.

  #uncover((2, 3))[
    On November 30th, 2019, Monero switched from its old POW algorithm, _cryptonight_, to RandomX. #uncover(3)[
      #text(fill: rgb("#f26822"))[Which had already been broken.]
    ]
  ]

  #uncover(3)[
    #l-m-hr()
    #quote(attribution: [tevador/RandomX], block: true)[
      RandomX uses random code execution (hence the name) together with several memory-hard techniques to minimize the efficiency advantage of specialized hardware.
    ]

    #l-m-meta[(Reminder: the goal is to make the CPU the perfect ASIC.)]

    #v(1em)

    https://github.com/tevador/RandomX
  ]
]

/*
- This is RandomX on a high level. This is supposed to resemble a CPU and this is supposed to be 2 GiB
  of fixed read only memory for it to sample from.

  The hash function accepts two input values:

  - String K with a size of 0-60 bytes (key)
  - String H of arbitrary length (the value to be hashed)

  and outputs a 256-bit result R.

  Intended use states that you fix the key, and you build the dataset from that which can take multiple
  seconds. Once the key is fixed you can use it like a regular hash function.

  You can think of these as two separate units, black boxes. The only thing the VM will
  ask the dataset is to read its items, which are 64 bytes in length each.

  As you can see in the corner there, the VM has a 2 KiB scratchpad which is basically its working
  memory, which is divvied up into L1, L2, L3. The point of the VM is to blast the scratchpad with entropy
  and then hash it along with it's registers. That's the final result.

  So what I'm going to do is look at these in separate pieces.
*/
#slide(
  background: image("randomx architecture simplified.png", fit: "cover", width: 120%, height: 120%),
)[]

/*
- (3) A hint here is that you actually don't need to lug around 2 GiB dataset, you can generate it on
      the fly from the dataset cache, which is only 256 MiBs.

      If you want to mine fast, you generate the entire 2 GiBs up front, but, if you just want to mine
      on a memory budget or verify someones hash, you only need the 256 MiB "cache" as you can run
      the 8 hash functions on demand. This is called light-verification, or light-mode.

      The most important thing to take from this slide is that the RandomX VM will ask for items,
      and those items are generated by executing 8 hash functions derived from the key.
      So these hash functions are generated just in time, they're just programs.
*/
#slide(
  background: image("randomx architecture dataset.png", fit: "cover", width: 110%, height: 110%),
  inset: 1.2em
)[
  #set align(top)
  #set text(size: 0.8em)

  #grid(columns: (10fr, 9fr), gutter: 0em, gc[], gc[
    #uncover((2, 3))[
      Pre-initialisation.

      - The key $K$ is passed to the SSH generator, which generates 8 hash functions.
      - $K$ is also used to fill 256 MiBs of static memory.
    ]

    #uncover(3)[
      #l-m-hr()
      Dataset-initialisation.

      - Each 64-byte Dataset item is generated by executing each of those 8 functions, and XORing data from the cache.
      - Cache $==>$ Dataset.
    ]
  ])
]

/*
*/
#slide(title: [(2.RX) Superscalar?], inset: 1em)[
  #set align(top)

  CPUs are _very_ good at executing arbitrary code.

  #grid(columns: (5fr, 4fr), gutter: 1em, gh[
    #set align(top)
    #v(1em)
    
    ```yasm
        add rax, rbx      ; (1) a = a + b
        imul rcx, rdx     ; (2) c = c * d
        sub rbx, 5        ; (3) b = b - 5
    ```
    #uncover((2, 3, 4, 5, 6, 7))[
      ```yasm
          ; (1) (2) (3) executed all at once (superscalar)
      ```
    ]
    ```yasm
        and rax, rcx      ; (4) a = a & c
        cmp rbx, 0        ; (5) test b with 0
    ```
    #uncover((3, 4, 5, 6, 7))[
    ```yasm
        ; (3) -> (5). (OoO-execution)
    ```
    ]
    
  ], gh[
    #v(1em)

    #uncover((4, 5, 6, 7))[
      ```yasm
        ; OoO, bundle (3) with (5).
        ; superscalar, execute both bundles at once
        add rax, rbx      ; (1) a = a + b
        imul rcx, rdx     ; (2) c = c * d
        and rax, rcx      ; (4) a = a & c

        sub rbx, 5        ; (3) b = b - 5
        cmp rbx, 0        ; (5) test b with 0
      ```
    ]
  ])
  #uncover((4, 5, 6, 7))[
    #l-m-hr()
  ]
  #grid(columns: (5fr, 4fr), gutter: 1em, gc[
    ```yasm

        jg l0             ; (6) if (b > 0) goto l0;
        mov rdx, rax      ; (7) d = a
    l0:
        xor rax, rax      ; (8) a = 0
    ```
    #uncover((5, 6, 7))[
      ```yasm
          ; (BP and speculative execution)
          ; at (6), optimistically guess that (b > 0) and
          ; skip straight to executing (8), aborting if wrong
      ```
    ]
  ], gc[
    #uncover((6, 7))[
      ```yasm

          add rax, rbx   ; writes to rax
          ;                ... code that uses rax
          mov rax, 5     ; also writes to rax
          ;                ... code that uses rax
      ```
    ]
    #uncover(7)[
      ```yasm


          ; RR will rename rax -> r0, execute the
          ; mov bundle with the add bundle.
      ```
    ]    
  ])
]

/*
- (1) If you didn't get all that, that's okay. The important things to take away is that CPU's are:
- (6) ... this to drive away ASICs. I'll give an example of how SuperscalarHash function is generated.
*/
#slide(title: [(2.RX) Superscalar?], inset: 2em)[
  CPUs are:

  #uncover((2, 3, 4, 5, 6))[
    1. Superscalar #l-m-meta[(execute multiple instructions at once)]
  ]
  #uncover((3, 4, 5, 6))[
    2. OoO-execution #l-m-meta[(reorder instructions)]
  ]
  #uncover((4, 5, 6))[
    3. Speculative execution #l-m-meta[(optimistically guess branches)]
  ]
  #uncover((5, 6))[
    4. Register renaming #l-m-meta[(more registers than it seems)]
  ]

  #uncover(6)[
    #v(1em)
    All of these increase Instruction-Level-Parallelism (ILP).
    
    #l-m-hr()

    Generated code in RandomX needs to take advantage of this!
  ]
]

/*
- CPU ..., generating code to saturate its ALU.

- NOTE: These are integer instructions only! The RandomX VM also uses floating point.
*/
#slide(title: [(2.RX) Maximising ILP])[
  #quote(block: true, attribution: [6\. SuperscalarHash (spec)])[SuperscalarHash is a custom diffusion function that was designed to burn as much power as possible using only the CPU's integer ALUs.]

  #v(1em)
  
  - RandomX wants to increase ILP,
  - so superscalarhash-functions are generated by simulating a reference superscalar CPU #l-m-meta[(Intel Ivy Bridge µarch)].

  #l-m-hr()

  - It assumes a CPU with 3 parallel integer execution ports (P0, P1, P5).

    #l-m-meta[(Multiplication can only run on P5, etc.)]
    
  - Schedules an instruction on every available port, for every cycle.
]
/* TODO: add in uncover */


/*
- (1) After each execution of a SuperscalarHash, the next cache index is set to the register that has the
      longest dependency chain in that superscalarhash to minimise how much a would be ASIC could
      parallelise the execution of the hash and force execution to be overall a straight line where
      CPUs excel.

- (2) And that's it! This is the entire Dataset side of RandomX. If you want to do light-mining or
      verification, the RandomX VM will call this `getItem` every time it needs to access the dataset.

      If you're not doing light-verfication and want to mine, just generate all of the 2 GiB dataset
      items ahead of time, which will take a couple seconds.

- (3) If you think that we could stop here and make this our RandomX, as it's pretty good already,
      know that this minus the cache is a part of what Tor uses for it's client puzzles. All the
      techniques for burning through a CPUs ILP is replicated in Equi-X, among others.
*/
#slide(title: [(2.RX) SuperscalarHash], inset: 1em)[
  #set align(top)

  #grid(columns: (5fr, 4fr), gutter: 1em, gc[
    = *Algorithm.*

    #v(1em)

    ```
    cacheIndex = item number
    r0 = (item number + 1) * 6364136223846793005
    r1 = r0 ^ 9298411001130361340
    
    i = 0
    do {
        block = cache[cacheIndex % nr. 64 bytes in cache]
        SuperscalarHash[i](r0, r1, r2, r3, r4, r5, r6, r7)
        r0..7 ^= block[0..7]
        cacheIndex = r[longest dependency chain]
        i = i + 1
    } while(i < 8)

    item data = (r0|r1|r2|r3|r4|r5|r6|r7)
    ```

    #uncover((2, 3))[
      #l-m-hr()    
      #l-m-meta[(That's really all there is to the Dataset.)]
    ]
    #uncover(3)[

      https://github.com/tevador/equix #l-m-meta[(Tor)]
    ]
  ], gc[
      #set text(size: 0.8em)
      ```yasm
      getItem:
        ; r0 = (itemNumber + 1) * 6364136223846793005
        mov r8, rdi
        add r8, 1
        mov rax, 6364136223846793005
        imul r8, rax

        ; r1 = r0 ^ 9298411001130361340 ... and so on for r2-r7
        mov r9, -9148333072579190276   ;
        xor r9, r8                     ; r9 (r1) = r0 ^ constant
        mov r10, -6381431487974942650  ;
        xor r10, r8                    ; r10 (r2) = r0 ^ constant
        ; ...
        ; ...
        ;
        ; execute SuperscalarHash[i](r0, ..., r7)

        ; each invocation is unrolled in the generated code,
        ; no loop here.
        imul r12, r15             ; IMUL_R r4, r7
        imul r13, r14             ; IMUL_R r5, r6
        imul r10, r11             ; IMUL_R r2, r3
        lea r14, [r14 + r11*2]    ; IADD_RS r6, r3 (shift 1)
        xor r15, r9               ; IXOR_R r7, r1
        mov rax, -1727223807      ;
        xor r8, rax               ; IXOR_C r0, imm32
        sub r15, r14              ; ISUB_R r7, r6 (going down ↓)
        ; ...................
      ```
  ])
]

/*
- So, to recap:
*/
#slide(
  background: image("randomx architecture dataset.png", fit: "cover", width: 110%, height: 110%),
  inset: 1.2em
)[
  #set align(top)
  #set text(size: 0.8em)

  #grid(columns: (10fr, 9fr), gutter: 0em, gc[], gc[
    Pre-initialisation.

    - The key $K$ is passed to the SSH generator, which generates 8 hash functions.
    - $K$ is also used to fill 256 MiBs of static memory.

    #l-m-hr()
    Dataset-initialisation.

    - Each 64-byte Dataset item is generated by executing each of those 8 functions, and XORing data from the cache.
    - Cache $==>$ Dataset.
  ])
]
/*
- An important thing to remmeber here is that we can generate the 2 GiBs of the
  dataset upfront and store it straight in DRAM. Or, which is slower, generate
  each dataset item on the fly when we need it.
*/

/*
- (1) What we want to achieve with the dataset is simple. The goal is
      memory hardness, which is a property of functions that are hard
      to evaluate efficiently without a large amount of memory.

      This is pretty fitting for RandomX, as CPUs have access to memory controllers, so that means reading, writing and prefetching up to
      tens of gigabytes of DRAM.

      Let's consider two ASIC designs to beat the CPU's slow external DRAM,
      so the goal is to somehow put the memory on-chip.

- (4) An ASIC for fast mode mining at the time of RandomX's introduction
      would simply be not possible, as 2 GiBs of memory would be 
      economically infeasible to store on-chip. You would lose out of the 
      advantage of on chip memory, and would have to use external DRAM, 
      then at that point there is no advantage to a CPU.
*/
#slide(title: [(2.RX) Memory-Hardness])[

  #uncoverb(2)[*Goal.* Sufficient memory-hardness.]
  #uncoverb(3)[
    #l-m-meta[(Let's consider two ASIC designs!)]
  ]

  #l-m-hr()

  #uncoverb(4)[
    - *(1)* 2 GiBs of on-chip low latency SRAM
      
      #uncoverb(6, l-m-meta[(An ASIC for fast mode mining is infeasible.)])
  ]
  #uncoverb(5)[
    #v(1em)
    $==>$ Try to make light mode mining viable?
    #v(1em)
  ]
]

/*
- (2) ... So, this ASIC will only store the cache, and execute the
      8 superscalarhash instances. Is that much slower?

- (3) Because the superscalarhash generator, which is a CPU simulator, 
      tries its hardest to maximise the dependency chain for all the 
      registers across the instructions so an ASIC can't just evaluate the 
      entire hash in parallel. Since each instruction depends on the 
      previous one maximally, OoO execution and the superscalar nature of 
      CPUs will be able to evaluate it efficiently. An ASIC would lose a 
      lot of efficiency on the performance front.

- (4) Also, it uses an incredible amount of power. Equivalent to just using
      external DRAM like a regular CPU.

- (5) No advantage over CPU, not in speed, or even in energy usage. Hence,
      this insentivises any ASIC to use external DRAM like CPUs. So 
      RandomX actually succeeds in being memory hard.
*/
#slide(title: [(2.RX) Memory-Hardness])[
  Let's try a competitive light mode mining ASIC?
  
  #uncoverb(2)[
    - *(2)* Light mode mining, 256 MiB of on-chip memory, 1-cycle latency for ops.
  ]

  #uncoverb(3)[
    #set text(size: 1em, l-m-meta-colour)

    #v(1em)

    The average SuperscalarHash function contains a total of 450 instructions, out of which 155 are 64-bit multiplications. On average, the longest dependency chain is 95 instructions long.
  
    \[...\]

    #uncoverb(4)[
      It will have to execute 155 \* 8 = 1240 64-bit multiplications per item, which will consume energy comparable to loading 64 bytes from DRAM.
    ]
  ]
  #v(1em)

  #uncoverb(2)[*Result.*] #uncoverb(5)[
    No advantage over CPU.
  ]
]

/*
- (1) So, given that we know that the Dataset takes advantage of the fact
      that CPUs are superscalar, and that Dataset initialisation is uniquely
      memory hard in the sense that creation of an ASIC that calculates the
      dataset ahead of time compared to calculating the items on demand, either
      has no advantage over a CPU.

- (2) Could we stop here? Consider an alteration of the dataset side of RandomX,
      with a new hash function that takes in a fixed key K and a large integer N,
      somehow hypothetically being an index into some dataset item.

      Assuming this is a good hash function: have we done enough?

- (3) The answer is not really, we do win memory hardness, but the fact that
      the superscalar hashes are superscalar isn't that useful. It's only to
      discourage the light mining ASIC design by burning huge amounts of energy,
      giving it no advantage over superscalar CPU designs.

      We only win memory hardness here.

      So, we need a whole other execution model, the RandomX VM, where as much
      of the CPU's capabilities are used.

- (9) Remember the goal here, we want to make the creation of an ASIC for RandomX
      as economically infeasible as possible, and which if an ASIC were to be
      created, it would resemble a CPU.

      Hence, every feature we include here that CPUs already have will
      increase the die area, the chip size, which will make it very expensive to
      manufacture a custom ASIC.
*/
#slide(
  background: image("randomx architecture dataset 1.png", fit: "cover", width: 110%, height: 110%),
  inset: 1em,
)[
  #set align(top)
  #set text(size: 0.9em)

  #grid(columns: (12fr, 10fr), gutter: 0em, gc[], gc[
    #uncoverb(2)[*Could we stop here?*]

    #uncoverb(3)[
      Not really.
    
      #l-m-meta[(Superscalar enables memory-hardness.)]

      #l-m-hr()
    ]

    #uncoverb(4)[
      #list[Superscalar instructions.]
    ]

    #uncoverb(5)[
      #list[Readable/writable memory.
        
        #l-m-meta[(L1, L2, L3 caches.)]
      ]
    ]


    #uncoverb(6)[
      #list[Instruction decoding.
      
        #l-m-meta[(μop cache)]
      ]
    ]
    
    #uncoverb(7)[
      #list[Floating point (IEE754), SIMD, (more) ALU.]
    ]

    #uncoverb(8)[
      #list[Branches/branch prediction.]
    ]

    #uncoverb(9)[
      #list[Native AES.]
    ]

    #uncoverb(10)[
      #l-m-hr()

      *Each increases die area for an ASIC!*
    ]
  ])
]

/*
- (1) Going back to the high level view, here is a recap.
      
      TODO
*/
#slide(
  background: image("randomx architecture simplified.png", fit: "cover", width: 120%, height: 120%),
)[]

/*
- (1) We have that they RandomX virtual machine is only concerned with the
      input hash bytes, not so much the key.

      On a high level there are four main sections of the VM, which are the
      scratchpad (which is the working memory of this imaginary CPU), the
      program buffer (which just holds the instructions), the register file,
      and the abstract virtual machine which describes the way to execute
      each program.

      You can follow the yellow lines as the flow of initialisation bytes,
      and the purple lines as the result flow, like the image for the dataset.

- (2) I will go through the general algorithm, and make note of some of the
      cryptographic primitives used.

- (3) An initial seed is calculated by hasing the input using Blake2b, then
      the scratchpad is entirely filled from random bytes using AesGenerator1R,
      which is a RandomX specific random bytes generator that uses one round
      of AES to mix up the state.

- (4) The program buffer is filled, which is basically all the state needed
      to program an instance of the RandomX virtual machine. 128 bytes are
      set aside to be loaded into the register file, and 2048 bytes is the
      actual program.

      This uses AesGenerator4R, which is the same as 1R, but uses 4 rounds
      of AES. The previous state of the 1R generator is fed into the 4R
      generator.

      An important thing to note is the choice of using AES here, most CPUs
      have a native instruction set for calculating AES rounds (AES-NI on
      Intel, same exists for Arm and Risc-V), which we mentioned before.

      The AES generators are sufficient in an avalanche of the input bits,
      but, the generator is reversible and doesn't make for a good hash
      function, which is why it is always initialised with a non-reversible
      hash function which is Blake2b with the seed there.

      The VM is executed along with all the instructions, filling up the
      scratchpad and register files with entropy, and reading from the
      dataset. I'll explain the instruction set later on.

      Last, the register file is hashed with Blake2b and copied to the
      AesGenerator4R* state which we're keeping around to generate
      an entirely new program, going around steps 3-5 again.

      The important thing to note here, is that we execute 8 randomly
      generated programs, where the output of one program is used to
      generate the program after. The reasons for this will come in
      the next slide.

- (5) So after we executed the 8 programs, we have a scratchpad which
      is just filled with entropy, so we hash it using the 1R generator
      (which is fast), and the final result is calculated as the hash of
      the scratchpad with a portion of the register file with Blake2b.
*/
#slide(
  background: move(dy: 8pt, image("randomx architecture vm.png", fit: "cover", width: 100%, height: 100%)),
  inset: 1.2em
)[
  #set align(top)
  #set text(size: 0.8em)

  #grid(columns: (17fr, 24fr), gutter: 0em, gc[
    #uncoverb(2)[
      *Algorithm.*
    ]

    #uncoverb(3)[
      1. Initial seed S is calculated. #l-m-meta[(Blake2b)]
      2. Scratchpad is filled. #l-m-meta[(AesGenerator1R=S)]
    ]

    #uncoverb(4)[
      #l-m-hr()

      3. Program Buffer filled. #l-m-meta[(AesGenerator4R\*)]

        #l-m-meta[(VM is programmed from contents)]
      
      4. *The VM is executed.*
      5. Register file is hashed and copied to AesGenerator4R\* state.
      6. Steps 3-5 are performed *8* times.

        #l-m-meta[(chained VM execution)]
    ]

    #uncoverb(5)[
      #l-m-hr()

      7. Scratchpad fingerprint is calculated. #l-m-meta[(AesGenerator1R)]
      
      8. Final result R is the hash of scratchpad fingerprint + register file. #l-m-meta[(Blake2b)]
    ]
  ], gc[])
]

/*
- (1) There is a very good reason RandomX opts to execute 8 different
      programs in a chain.

- (2) Remember that mining is simply just finding an integer called
      the nonce that when you concat the block data, which is the 
      transactions, with the nonce it hashes to a value that is 
      acceptible, within a certain difficulty.

- (3) Given this, since the nonce can be any number, why not just
      optimise for the easy programs, and skip the hard ones?

- (4) Well, if you had to execute multiple programs in a chain, aborting
      on an unfavourable program would be pretty expensive because you'd
      have to throw away all your previous work. Even if you were quicker
      at the easy programs, the fact that you need to do 8 whittles down
      your advantage back to nothing.

      So, RandomX doing 8 chained programs in a row means that you're 
      forced to commit to executing them all, otherwise you'd be much
      slower than just biting the bullet and doing it the honest way.
*/
#slide(
  background: move(dy: 25%, image("randomx easy program problem.png", fit: "contain", width: 100%, height: 100%)),
  title: [(2.RX) Easy program problem],
)[
  #set align(top)

  #gc[
    #uncoverb(2)[
      - Mining is evaluating HASH(block $⊕$ nonce), where nonce = 0, 1, 2, ...

        #l-m-meta[(until a successful hash is found.)]
    ]

    #uncoverb(3)[#list[Why not just nonce++ when an unfavorable #l-m-meta[(hard)] program is found?]]
    
    #uncoverb(4)[
      #l-m-hr()

      *Reason.* Chaining programs forces you to commit, or take a #l-m-meta[(time)] penalty.
    ]
  ]
]

/*
- (1) So, we are memory hard, but that's only for reading, so we're not
      taking advantage of the caches that exist in a CPU already.

- (2) Remember that CPUs have caches for frequently acccessed memory, and
      in basically all CPUs it's organised into an L1, L2, L3 hierarchy,
      with L1 being the closest to a core often being exclusively owned
      by a core, L2 being larger and slightly slower, holding data evicted
      by L1, and L3 being the largest and shared among most or all cores.

- (3) Every instruction that can read or write will do so respecting the
      hierarchy, so accesses to L1 are done 3 times as much as accesses to
      L2, and accesses to L3 are done sparingly and at certain stages to
      avoid stalls.

- (4) The image below shows the distribution of writes to the scratchpad,
      it's divided up into three sections with the far left being L1,
      middle left being L2, and the entire right being L3. Each red pixel
      represents 8 bytes being overwritten.
*/
#slide(
  title: [(2.RX) Scratchpad],
)[
  - Memory-hard, but don't R/W? #l-m-meta[(Forgetting L1, L2, L3?)]
  
  #uncoverb(2)[
    #l-m-hr()
    
    #list[The scratchpad is meant to mirror L1, L2, L3 present in typical CPUs.]
  ]

  #uncoverb(3)[
    - Each inst. that can R/W, will do so respecting the hierarchy.

      16 KiBs #l-m-meta[(L1)] $subset.eq$ 256 KiBs #l-m-meta[(L2)] $subset.eq$ 2 MiBs #l-m-meta[(L3)]
  ]
  

  #uncoverb(4)[
    #l-m-hr()
    #set align(center)
    #image("L1 L2 L3.png", width: 80%)
  ]
]

/*
- (1) The virtual machine has 8 integer registers r0-r7 and a total of 12
      floating point registers split into 3 groups, f0-f3, e0-e3, a0-a3.
      Group R registers are 64 bits wide, and each floating point register
      is 128 bits wide, which transparently is just a pair of two doubles
      that aren't separately addressible, so operations on the VM's FP
      registers can be compiled down to operations on SIMD registers.

      The FP registers a0-a3 are fixed from when the VM was programmed.
      You could view the f0-f3 registers as "additive" registers and,
      e0-e3 as "multiplicative" registers.

      There are also 3 internal registers, ma, mx, and fprc. You might have
      already seen ma and mx, they're the registers that store an index
      into the dataset item to access.

      fprc is a special register which denotes the current 4 rounding 
      modes, I'll talk about this more as well as the FP register classes 
      when later on.

      amd64 is the lowest common denominator over all of the ISAs RandomX
      wants to support, so only 8 integer registers and 12 SIMD registers,
      and all of the VM instructions are two address x86 style, so two
      operand, writing to the first one. All of the other ISAs, like Risc-V
      and Arm have more integer registers and support actual
      three address code.

- (2) The integer instructions are pretty standard...

      No division is included, but IMUL_RCP is multiplication by the
      a reciprocal, so division by some fixed 32 bit value. The reason
      being is division exists on CPUs, but isn't pipelined/fast, but
      you wouldn't want to exclude division. Calculating the reciprocal
      requires a division, so including IMUL_RCP forces ASICs to include
      a division circuit which CPUs already have.

      Note that most of these instructions have _R and _M variants, which
      read and write registers, or read and write to the scratchpad.

      TODO:

- (3) The only floating point operations that are included are the
      base deterministic IEEE754 instructions, swapping the pair within
      an FP register, and FSCAL which performs a scaling according to
      some complex rules which is equivalent to a XOR on the floating
      point binary representation.

      The reason why FSCAL exists, which works on the F registers, is so
      that ASICs can't use a quicker fixed point representation over using
      IEEE doubles. If they used a fixed point representation, they'd need
      to follow the complex scaling rules, where if it's in IEEE format,
      a simple XOR gives it to you for free.

- (4) Stores into the scratchpad are done with ISTORE. Loops are implemented
      using CBRANCH, and the generation is set up in a way so that upwards
      branches don't nest, and infinite loops can't happen.

      Superscalar designs CPU designs have a huge advantage here executing
      the code with the FP and integer instructions, as well as speculative
      execution around branches.

      The CFROUND instruction adjusts the rounding mode of the add, sub,
      mul, div, and square root, just the IEEE instructions. The default
      setting of fprc is zero, which is the default assumed rounding mode 
      for basically all programming languages.

*/
#slide(title: [(2.RX) Instructions + Registers], inset: 1.2em)[
  #let gb = gc.with(height: 60%)

  #set align(top)
  
  #grid(columns: (10fr, 10fr), gutter: 1em, gb[
    #uncoverb(2)[
      *Instructions (integer).*

      - IADD, ISUB, IMUL, IMULH, ISMULH, INEG
      - IXOR, IROL, ISWAP_R
      - IMUL_RCP #l-m-code[(division by imm32)]
    ]

    #uncoverb(3)[
      #l-m-hr()
      
      *Instructions (FP).*

      #l-m-meta[(IEEE754)] FADD, FSUB, FMUL, FDIV, FSQRT

      - FSWAP_R: #l-m-code[(dst0, dst1) = (dst1, dst0)]
      - FSCAL_R: #l-m-code[(XOR by 0x80F0000000000000)]
    ]
  ], gb[
    #uncoverb(4)[
      *Instructions (misc).*
      - ISTORE: _arbitrary_ scratchpad addr.

      - CBRANCH: backwards branch, flat loops
      - CFROUND: change FP rounding #l-m-meta[(IEEE754)]

        (adjusts *fprc* = 0, 1, 2, 3)

      #[
        #set text(size: 0.8em)
        #set align(center)

        #table(
          columns: (auto, auto),
          stroke: luma(70),

          [0], [roundTiesToEven],
          [1], [roundTowardNegative],
          [2], [roundTowardPositive],
          [3], [roundTowardZero],
        )
      ]
    ]
  ])

  #[
    #set align(right)
    #uncoverb(2)[
      #l-m-meta[(most instructions have \*\_R, \*\_M variants)]
    ]
    #linebreak()
  ]
  
  #block[
    #set align(left)
    #let sz(d) = (auto,) * d
    #set par(spacing: 0pt)
    #let except(d, i) = (x, _) => if x == i {} else {d}
    #let initsp = 12em

    #table(
      columns: (initsp,) + sz(8),
      stroke: except(l-m-meta-colour, 0),
      fill: except(rgb("#ff000075"), 0),
    )[#l-m-meta[(64-bit integers)]][r0][r1][r2][r3][r4][r5][r6][r7]

    #table(
      columns: (initsp,) + sz(12),
      stroke: except(l-m-meta-colour, 0),
      fill: (x, _) => {
        if x == 0 {}
        else if x <= 4 { rgb("#016fff56") }
        else if x <= 8 { rgb("#01ff7356") }
        else { rgb("#ff01ff56") }
      }
    )[#l-m-meta[(pairs of doubles)]][f0][f1][f2][f3][e0][e1][e2][e3][a0][a1][a2][a3]

    #table(
      columns: (initsp,) + sz(3),
      stroke: except(l-m-meta-colour, 0),
    )[#l-m-meta[(misc)]][ma][mx][fprc]
  ]
]

#let Ru = math.upright("R")
#let RD = $upright(bold("RD"))$
#let RU = $upright(bold("RU"))$
#let RN = $upright(bold("RN"))$
#let RZ = $upright(bold("RZ"))$

/*
- (1) Before I conclude, I want to go over floating point numbers and give a
      quick and dirty explaination.

- (2) The most common example is 0.1 + 0.2 != 0.3. This sets a lot of people
      off because this is just not what you should be expecting at all.
      Numbers are numbers, so why are floats just lying here?

- (3) The easiest way to explain this is just that a floating point numbers
      make a tradeoff between performance and ease of use, over actually
      representing the numbers they represent.

      The floating point standard IEEE754 for double precision, which is what
      we care about in this presentation, uses in short, base 2 numbers in
      scientific notation. So the only numbers that you write down in your 
      programs that are strings of integer powers of 2, those are the only ones
      that can actually be exactly represented.

- (4) Simplifying a lot, because of maths, representing an arbitrary real 
      number
      takes an infinite amount of space. Imagine a number line, and you just
      pointed to a random number on it. If you picked that real number at 
      random, the chances that it is a number that can be represented in a 
      finite amount of space is actually zero.

      We don't have an infinite amout of memory, so representing real numbers 
      exactly is just not possible.

      IEEE754 double precision defines a 64 bit wide floating point number, so 
      there is only less than 2^64 possible numbers compared to the infinite 
      amount of real numbers. For simplicity, and because RandomX doesn't need 
      it, we don't consider NaN here.

- (5) We also have that the set of floating point doubles R contains positive 
      and negative infinity.

- (6) So to recap, ...

- (7) But, I haven't actually addressed the elephant in the room, which is that
      programmers working with floating point numbers find it frustrating,
      inaccurate, and basically a random black box.

      If floating point feels random and like magic, why should RandomX rely on it to give consistent results?
*/
#slide(title: [(2.RX) IEEE754])[
  #uncoverb(2)[
    - 0.1 + 0.2 = 0.30000000000000004 != 0.3 #l-m-meta[(?? wtf)]
  ]

  #uncoverb(3)[
    - *IEEE754* makes a _tradeoff_. #uncoverb(4)[Define $Ru$ as set of _doubles_ without NaN. Then $|Ru| < 2^64$.]

      #uncoverb(5)[Define $RR^infinity = RR union { +infinity, -infinity}$, then $Ru subset RR^infinity$. #l-m-meta[(this is just $overline(RR)$)]]
  ]

  #uncoverb(6)[
    #l-m-hr()

    *Result.* $Ru$ is a finite amount of useful numbers, with $plus.minus infinity$. #l-m-meta[(IEEE754)]
  ]

  #linebreak()

  #uncoverb(7)[
    #figure[
      But... what about inaccuracies, rounding? FP is random??
    ]
  ]
]

/*
- (2) What does correctly rounded mean? It basically is, take two numbers,
      do an operation with infinite precision, like mathematical addition, 
      then round it down back into a floating point number.

      The 5 core operations of IEEE754 are defined this way, for example
      addition of x and y is just taking those two numbers, adding them
      as you would like real numbers, then rounding down which will basically
      crunch the number back to something within range that the double can
      actually represent.

- (3) There are actually 4 different ways to round a number so that it goes back
      into being a double. All of them are specified by IEEE, which are
      - round to nearest,
      - round towards negative infinity,
      - round towards positive infnity,
      - round towards zero.
      
- (4) If you do any of these primitive operations on floats, you can expect the
      CPU to round your numbers according to these 4 different rounding modes,
      which there is usually an inbuilt register inside your CPU to select a
      rounding mode globally, not per instruction.

      So, the RandomX "fprc" is an integer from 0-3 which stores the current
      rounding mode, and the floating point instructions defined a couple slides
      ago use the global rounding mode.

      CPUs already have these 4 rounding modes, and there is a lot of die space
      on them dedicated to performing the 5 operations, so if RandomX only used
      round to nearest, it would be missing out.

      Also the fact that fprc is global, it's not per instruction. So the CPUs
      have this internal register state which can be modified to switch out
      entire circuits at runtime, which ASICs would need to add.

- (5) Now, an important thing to understand is that if you have any experience
      with programming languages like python, javascript, or rust, all of them
      only ever provide RN and most people don't think that the others exist.

      In javascript, you just can't get other rounding modes, and python and
      rust you need external bindings. In rust, it's actually undefined 
      behaviour if you are to modify the global rounding mode.
      
      This would be a problem if you are going to implement RandomX in one of
      those languages.

      So what you need to take away from this slide, is that floating point
      numbers are under IEEE754 are perfectly defined and portable, they just
      have a decent amount of internal machinery to do with rounding.
*/
#slide(title: [(2.RX) IEEE754])[
  #gh(height: 60%)[
    FP is perfectly specified, with $+$, $-$, $times$, $div$, $sqrt(.)$ *correctly rounded*.

    #uncoverb(2)[
      - $"fadd_n"(x, y) = RN(x + y)$, $"fsqrt_n"(x) = RN(sqrt(x))$, etc.
    ]

    #uncoverb(4)[
      #l-m-hr()

      Define $circle.small : RR^infinity -> Ru$ to be a function that rounds according to a #l-m-meta[(global)] fprc.

      - $"fadd"(x, y) = circle.small(x + y)$, $"fsqrt"(x) = circle.small(sqrt(x))$, etc.
    ]

    #v(1em)

    #uncover(5)[
      #figure[
        *All P/L give you $RN$ only.* \
        #l-m-meta[(foreshadowing)]
      ]
    ]
  ]

  #grid(columns: (10fr, 10fr), gutter: 1em, gh[
    #uncoverb(4)[
      ```
      ○(x) {
        case fprc = 0: RN(x)
        case fprc = 1: RD(x)
        case fprc = 2: RU(x)
        case fprc = 3: RZ(x)
      }
      ```
    ]
  ], gh[
    #set text(size: 0.8em)
    #set align(right)
    
    #uncoverb(2)[
      #table(
        columns: (auto, auto, auto),
        stroke: luma(70),
        align: left,

        table.header(
          [*fprc*]
        ),
        [0], [roundTiesToEven], [$RN : RR^infinity  -> Ru$],
        [1], [roundTowardNegative], [$RD : RR^infinity -> Ru$],
        [2], [roundTowardPositive], [$RU : RR^infinity -> Ru$],
        [3], [roundTowardZero], [$RZ : RR^infinity -> Ru$],
      )
    ]
  ])
]

/*
- (1) Calling back to the first slide in this part...
*/
#slide(title: [(2.RX) Conclusion])[
  #quote(attribution: [tevador/RandomX], block: true)[
    RandomX uses random code execution (hence the name) together with several memory-hard techniques to minimize the efficiency advantage of specialized hardware.
  ]

  #l-m-meta[(Reminder: the goal is to make the CPU the perfect ASIC.)]

  #l-m-hr()

  #grid(columns: (13fr, 9fr), gutter: 1em, gh[
    #uncoverb(2)[
      An ASIC for RandomX needs:

      - 2 GiBs of #l-m-meta[(external)] DRAM - *Memory-hard*
      - *Random* code execution.
      - Superscalar design, instruction/μop cache.
      - Speculative execution, branches.
      - Full compliant IEEE754.
      - Hardware dividers.
      - Hardware AES, SIMD floating point.
      - 2 MiBs of scratchpad (L1, L2, L3).
    ]
  ], gh[
    #uncoverb(3)[
      *Verdict.* No advantage over CPU.

      #l-m-meta[(economically infeasible)]
    ]

    #linebreak()

    #uncoverb(4)[
      *Success!*
    ]
  ])
]

#new-section-slide[(3.JS) RandomX.js]

/*
- (1) ..., which is just executing a script in the browser to mine coins, mostly at
      a pretty large performance hit to native.

- (2) It could replace ads, but it's just used for stealing hashrate from hacked
      websites by installing a script without them knowing.

      For example, the pirate bay, to gain some extra revenue, used a service called
      coinhive, where they just put a <script> tag inside their website, which mined monero. coinhive as a company basically disappeared into thin air around the
      same time RandomX came to be.

- (3)
- (4) So, the question really is, why?
*/
#slide(title: [(3.JS) RandomX.js?])[
  Monero has a certain relationship with Web Mining.

  #uncoverb(2)[
    - _Could_ replace ads, just used for cryptojacking websites.
      
      _The Pirate Bay_ used *Coinhive*. CH discontinued in 2019.
  ]

  #l-m-hr()
  
  #uncoverb(3)[
    No *serious/working* implementations since RandomX was introduced.

    #l-m-meta[(suggesting that one could be implemented was laughable)]
  ]


  #linebreak()

  #uncoverb(4)[
    #figure[
      *Why?*
    ]
  ]
]

/*
- (1) ...
      It isn't really a matter of "can this be implemented", it's more of a,
      "can this be implemented and not be terribly slow".

      Remember, access to other floating point rounding modes is more of low level
      thing, given that you need to access non-portable processor state with inline
      assembly or some other library that wraps it for you. So most programming 
      languages are stuck with RN, round to nearest.

      Now, you can easily reimplement the hardware routines for the floating point
      rounding modes, it's just going to be slower than the hardware implementation.
      This is called "softfloat", floating point in software.

- (2) Tevador, the creator thinks that it can be done, just really slowly.
      Which he estimates 30 hashes a minute, which is less than 1 H/s.

      That's just, really really low. Like come on!

      I wanted to try beat that.
*/
#slide(title: [(3.JS) RandomX.js?])[
  #quote(block: true, attribution: [README.md])[
    *Does RandomX facilitate botnets/malware mining or web mining?*

    [...]

    Web mining is infeasible due to the large memory requirement and the lack of directed rounding support for floating point operations in both Javascript and WebAssembly.
  ]

  #set align(right)

  #l-m-meta[(Stuck with $RN$ !!)]

  #uncoverb(2)[
    #figure(image("image.png", width: 55%))
  ]
]

/*
- (1) ...

      People have asked me why I would decide to make such a thing, and it's really
      just a "because I wanted to" or because it's a nice engineering problem.

      RandomX being the huge monolith that it is got me very interested, and what
      tevador said really felt like a challenge.

- (2) The point of WebAssembly is to be a compilation target for performance
      sensitive code, it's basically assembly for the web, where you work with raw
      memory, unboxed integers, and so on.

      ... web workers, and they communicate by message passing.

      ... there are a lot of extensions to WASM that actually make it a pretty fast 
      contender over actual instruction sets.
      
      So, JavaScript can execute arbitrary code pretty fast at runtime, you just
      generate WebAssembly just in time, and get JavaScript to load and execute it
      for you!

- (3) There are some downsides, no AES instruction, and you're limited to a fixed
      rounding mode which is round to nearest, you don't have control over it.
      Which is the same as JavaScript, there is also no nice way to really
      model the ability to change the rounding mode, so it's just not in there.

      For AES, you can just reimplement it too, so it's not a big deal either.

      If there was an implementation, for it to be useful on a browser or Node.JS,
      don't even try allocating 2 GiBs, it's just not a reasonable thing, so we're
      suck to light mining.
*/
#slide(title: [(3.JS) RandomX.js])[
  #quote(block: true, attribution: [l1mey112/randomx.js])[
    RandomX.js is an implementation of the ubiquitous Monero POW algorithm RandomX in JavaScript. 
  ]

  #linebreak()

  #grid(columns: (45fr, 9fr), gutter: 1em, gh[
    #uncoverb(2)[
      *\~5 years later (2024):*

      - JavaScript has WebAssembly now, with SIMD and shared memory.
      - JavaScript has threads (web workers).
      - WASM is pretty expressive, with branch tables, memcpy(), etc.
    ]

    #linebreak()

    #uncoverb(3)[
      No native AES instruction, no $RD$, $RU$, $RZ$, and

      - *shouldn't* have 2 GiB dataset, so only light mining.

          #l-m-meta[(compute dataset items on fly, expensive...)]
    ]
  ], gh[
    #uncoverb(2)[
      #image("image-1.png")
    ]
  ])


  #l-m-hr()
  
  https://github.com/l1mey112/randomx.js
]

/*
- TODO

- (2) ...

      I guess the reason to use C, is because it just made sense to me at the time,
      and the tooling was there for WASM. I'd be working with mostly intrinsics and
      since all the memory I was working with was static buffers, it was no problem.

*/
#slide(title: [(3.JS) Overview])[
  #let C = rgb("#669ad3")
  #let TypeScript = rgb("#3077c5")
  #let linesof(x) = 100% * (x / 4500)
  #let except(d, i) = (_, y) => if y == i {} else {d}
  #let ll(body) = [#set text(fill: C); #set align(right); #body]

  #let gb = gc.with(height: 65%)

  #grid(columns: (45fr, 10fr), gutter: 1em, gb[
    #uncoverb(2)[
      - Complete impl. of core RandomX in #text(fill: C)[C], 5000 lines.
      - 500 lines of host _glue_ #text(fill: TypeScript)[TypeScript]. #l-m-meta[(to execute JIT VM)]
      - Same tests as RX, and 200k LOC test suite for FP impl. 
    ]

    #uncoverb(3)[
      #l-m-hr()

      - No interpreter, RX code generated in WASM and executed by JS.
      - Rewritten cryptography to use WASM SIMD.
      - Performant directed rounding, *semifloat*. #l-m-meta[(!!)]
      - Support for shared memory/threads.
      
        #l-m-meta[(i.e. share the 256 MiB cache)]
    ]
  ], gb[
    #uncoverb(2)[
      #image("image-3.png")

      #image("image-5.png")
    ]
  ])

  #linebreak()
  #linebreak()

  #uncoverb(2)[
    #table(
      columns: (linesof(2600), linesof(700 + 500), linesof(400), linesof(300)),
      stroke: except(l-m-meta-colour, 1),
      [RandomX WASM *JIT* - VM implementation], [Dataset/Crypto], [FP+mul], [VM],
      ll[2600 lines], ll[1200 lines], ll[400], ll[300],
    )
  ]
]

/*
- (3) ..., which is certainly a much better figure than the 1 H/s speculated by the
      creator. So I'd call this a win.
*/
#slide(title: [(3.JS) Performance?])[
  ```sh
  node examples/randomx.js
  # machine id: AMD Ryzen 7 3800X 8-Core Processor [rx/0+relaxed-simd+!fma] Node.js/v22.9.0 (linux x64)
  # cache construction time 535.8 ms
  # average hashrate: 22.0 H/s

  node examples/randomx_threaded.js
  # machine id: AMD Ryzen 7 3800X 8-Core Processor [rx/0+relaxed-simd+!fma] Node.js/v22.9.0 (linux x64)
  # initialising thread 0..15
  # average hashrate: 208.0 H/s
  ```

  #linebreak()

  #uncoverb(2)[
    On the same machine #l-m-meta[(with light mining)], I got 100 H/s per thread.
  ]

  #linebreak()

  #uncoverb(3)[
    #figure[
      *5x slower is pretty good!*
    ]
  ]
]

#slide(title: [(4.FP) Semifloat])[
  #show raw: set text(size: 0.75em)

  - During VM, a branch table #l-m-meta[(call_indirect)] selects correct FP  op w/ rounding.

  #linebreak()

  #grid(columns: (auto, auto), gutter: 1em, gh[
    ```c
    case FADD_R:
        // dst = dst + src
        WASM_U8_THUNK({
            0x20, F(inst->dst), // local.get $dest
            0x20, A(inst->src), // local.get $src
            0x23, $fprc,        // global.get $fprc
            0x11, 3, 0,         // call_indirect table 0
            0x21, F(inst->dst), // local.set $dest
        });
        break;
    ```
  ], gh[
    ```c
    WASM_SECTION(WASM_SECTION_ELEMENT, {
        WASM_U8_THUNK({
            5, // elems = vec(5)

            // elem 0: fadd
            0x02,
            0,                                  // table index = 0
            0x41, 0, 0x0b,                      // offset = i32.const 0
            0x00,                               // funcref
            4,                                  // elements = vec(4)
            FIDX(3), FIDX(4), FIDX(5), FIDX(6), // fprc_0..fprc_3
            // fadd_0,  fadd_1,  fadd_2,  fadd_3
            //
            // setup fsub_0-3, fmul_0-3, fdiv_0-3, fsqrt_0-3, ...
    ```
  ])

  #linebreak()

  #uncoverb(2)[
    The goal here is an implementation of $RD$, $RU$, $RZ$ in terms of $RN$.
  ]

  #uncoverb(2)[
    *Motivation.* You mostly want branchless code.
  ]
]

#slide(title: [(4.FP) Hardware, Software, Semi?])[
  #grid(columns: (auto, auto), gutter: 1em, gh[
  ], gh[
    
  ])
]


/*
- don't really show how it works in WASM
+ show the JS outside
+ show the why is FP is good
*/

/*
dedicate the last section to the JIT and FP math
RandomX.js
- features, and so forth
- then the JIT, and floating point emulation math
  implementation in SIMD performance, branch hinting
*/


/*
- TODO have a section to "show" the code!
*/