#import "polylux/polylux.typ": *
#import "polylux/l-m.dev.typ": *

#set raw(tab-size: 4)
#show: metropolis-theme.with()
#set par(justify: true)

#let l-m-todo(body) = [#text(fill: l-m-meta-colour)[\/\/ ]#text(fill: l-m-accent-colour)[TODO: ] #text(fill: l-m-meta-colour, body)]
#let l-m-tldr(body) = [#text(fill: l-m-meta-colour)[\/\/ ]#text(fill: l-m-accent-colour)[tldr: ] #text(fill: l-m-meta-colour, body)]
#let span-sep(left, right) = box[#left #box(width: 1fr, repeat[#text(fill: l-m-meta-colour)[-]]) #right]

#let l-m-meta(body) = text(fill: l-m-meta-colour, body)

#let uncoverb(b, body) = uncover((beginning: b), body)

#let gc = block.with(
  width: 100%,
  height: 100%,
)

#let gh = block.with(
  width: 100%,
)

#title-slide({
  l-m-title("Zero to RandomX.js")
  linebreak()
  l-m-title("")
  l-m-hr()
  set text(size: 0.8em)
  text(fill: l-m-meta-colour, "Tuesday, October 3rd | Lecture Theatre 123 | 6 PM - 8 PM")
})

#slide(title: "About me")[
  - Liam, l-m, #underline[l-m.dev], #underline[l-m\@l-m.dev]
]

#focus-slide()[
  Let Me Paint A Picture. TODO change this
]

/*
*/
#slide(title: "What is Monero?")[
  - Introduce
]


/* TODO: Required knowledge
    - Hashes
*/
#new-section-slide[(1.POW) Proof-of-Work Consensus]

#new-section-slide[(2.RX) RandomX]

/*
- (3) By then, ASICs for cryptonight have already been created, so the switch was needed.
*/
#slide(title: [(2.RX) RandomX])[

  RandomX is a proof-of-work algorithm that is optimized for general-purpose CPUs. It has stood the test of time as an *ASIC resistant* hash function.

  #uncover((2, 3))[
    On November 30th, 2019, Monero switched from its old POW algorithm, _cryptonight_, to RandomX. #uncover(3)[
      #text(fill: rgb("#f26822"))[Which had already been broken.]
    ]
  ]

  #uncover(3)[
    #l-m-hr()
    #quote[
      RandomX uses random code execution (hence the name) together with several memory-hard techniques to minimize the efficiency advantage of specialized hardware.
    ]

    #l-m-meta[(Reminder: the goal is to make the CPU the perfect ASIC.)]

    #v(1em)

    https://github.com/tevador/RandomX
  ]
]

/*
- This is RandomX on a high level. This is supposed to resemble a CPU and this is supposed to be 2 GiB
  of fixed read only memory for it to sample from.

  The hash function accepts two input values:

  - String K with a size of 0-60 bytes (key)
  - String H of arbitrary length (the value to be hashed)

  and outputs a 256-bit result R.

  Intended use states that you fix the key, and you build the dataset from that which can take multiple
  seconds. Once the key is fixed you can use it like a regular hash function.

  You can think of these as two separate units, black boxes. The only thing the VM will
  ask the dataset is to read its items, which are 64 bytes in length each.

  As you can see in the corner there, the VM has a 2 KiB scratchpad which is basically its working
  memory, which is divvied up into L1, L2, L3. The point of the VM is to blast the scratchpad with entropy
  and then hash it along with it's registers. That's the final result.

  So what I'm going to do is look at these in separate pieces.
*/
#slide-background(
  background: image("randomx architecture simplified.png", fit: "cover", width: 120%, height: 120%),
)[]

/*
- (3) A hint here is that you actually don't need to lug around 2 GiB dataset, you can generate it on
      the fly from the dataset cache, which is only 256 MiBs.

      If you want to mine fast, you generate the entire 2 GiBs up front, but, if you just want to mine
      on a memory budget or verify someones hash, you only need the 256 MiB "cache" as you can run
      the 8 hash functions on demand. This is called light-verification, or light-mode.

      The most important thing to take from this slide is that the RandomX VM will ask for items,
      and those items are generated by executing 8 hash functions derived from the key.
      So these hash functions are generated just in time, they're just programs.
*/
#slide-background(
  background: image("randomx architecture dataset.png", fit: "cover", width: 110%, height: 110%),
  inset: 1.2em
)[
  #set align(top)
  #set text(size: 0.8em)

  #grid(columns: (10fr, 9fr), gutter: 0em, gc[], gc[
    #uncover((2, 3))[
      Pre-initialisation.

      - The key $K$ is passed to the SSH generator, which generates 8 hash functions.
      - $K$ is also used to fill 256 MiBs of static memory.
    ]

    #uncover(3)[
      #l-m-hr()
      Dataset-initialisation.

      - Each 64-byte Dataset item is generated by executing each of those 8 functions, and XORing data from the cache.
      - Cache $==>$ Dataset.
    ]
  ])
]

/*
*/
#slide(title: [(2.RX) Superscalar?], inset: 1em)[
  #set align(top)

  CPUs are _very_ good at executing arbitrary code.

  #grid(columns: (5fr, 4fr), gutter: 1em, gh[
    #set align(top)
    #v(1em)
    
    ```yasm
        add rax, rbx      ; (1) a = a + b
        imul rcx, rdx     ; (2) c = c * d
        sub rbx, 5        ; (3) b = b - 5
    ```
    #uncover((2, 3, 4, 5, 6, 7))[
      ```yasm
          ; (1) (2) (3) executed all at once (superscalar)
      ```
    ]
    ```yasm
        and rax, rcx      ; (4) a = a & c
        cmp rbx, 0        ; (5) test b with 0
    ```
    #uncover((3, 4, 5, 6, 7))[
    ```yasm
        ; (3) -> (5). (OoO-execution)
    ```
    ]
    
  ], gh[
    #v(1em)

    #uncover((4, 5, 6, 7))[
      ```yasm
        ; OoO, bundle (3) with (5).
        ; superscalar, execute both bundles at once
        add rax, rbx      ; (1) a = a + b
        imul rcx, rdx     ; (2) c = c * d
        and rax, rcx      ; (4) a = a & c

        sub rbx, 5        ; (3) b = b - 5
        cmp rbx, 0        ; (5) test b with 0
      ```
    ]
  ])
  #uncover((4, 5, 6, 7))[
    #l-m-hr()
  ]
  #grid(columns: (5fr, 4fr), gutter: 1em, gc[
    ```yasm

        jg l0             ; (6) if (b > 0) goto l0;
        mov rdx, rax      ; (7) d = a
    l0:
        xor rax, rax      ; (8) a = 0
    ```
    #uncover((5, 6, 7))[
      ```yasm
          ; (BP and speculative execution)
          ; at (6), optimistically guess that (b > 0) and
          ; skip straight to executing (8), aborting if wrong
      ```
    ]
  ], gc[
    #uncover((6, 7))[
      ```yasm

          add rax, rbx   ; writes to rax
          ;                ... code that uses rax
          mov rax, 5     ; also writes to rax
          ;                ... code that uses rax
      ```
    ]
    #uncover(7)[
      ```yasm


          ; RR will rename rax -> r0, execute the
          ; mov bundle with the add bundle.
      ```
    ]    
  ])
]

/*
- (1) If you didn't get all that, that's okay. The important things to take away is that CPU's are:
- (6) ... this to drive away ASICs. I'll give an example of how SuperscalarHash function is generated.
*/
#slide(title: [(2.RX) Superscalar?], inset: 2em)[
  CPUs are:

  #uncover((2, 3, 4, 5, 6))[
    1. Superscalar #l-m-meta[(execute multiple instructions at once)]
  ]
  #uncover((3, 4, 5, 6))[
    2. OoO-execution #l-m-meta[(reorder instructions)]
  ]
  #uncover((4, 5, 6))[
    3. Speculative execution #l-m-meta[(optimistically guess branches)]
  ]
  #uncover((5, 6))[
    4. Register renaming #l-m-meta[(more registers than it seems)]
  ]

  #uncover(6)[
    #v(1em)
    All of these increase Instruction-Level-Parallelism (ILP).
    
    #l-m-hr()

    Generated code in RandomX needs to take advantage of this!
  ]
]

/*
- CPU ..., generating code to saturate its ALU.

- NOTE: These are integer instructions only! The RandomX VM also uses floating point.
*/
#slide(title: [(2.RX) Maximising ILP])[
  #quote[SuperscalarHash is a custom diffusion function that was designed to burn as much power as possible using only the CPU's integer ALUs.]

  #v(1em)
  
  - RandomX wants to increase ILP,
  - so superscalarhash-functions are generated by simulating a reference superscalar CPU #l-m-meta[(Intel Ivy Bridge µarch)].

  #l-m-hr()

  - It assumes a CPU with 3 parallel integer execution ports (P0, P1, P5).

    #l-m-meta[(Multiplication can only run on P5, etc.)]
    
  - Schedules an instruction on every available port, for every cycle.
]
/* TODO: add in uncover */


/*
- (1) After each execution of a SuperscalarHash, the next cache index is set to the register that has the
      longest dependency chain in that superscalarhash to minimise how much a would be ASIC could
      parallelise the execution of the hash and force execution to be overall a straight line where
      CPUs excel.

- (2) And that's it! This is the entire Dataset side of RandomX. If you want to do light-mining or
      verification, the RandomX VM will call this `getItem` every time it needs to access the dataset.

      If you're not doing light-verfication and want to mine, just generate all of the 2 GiB dataset
      items ahead of time, which will take a couple seconds.

- (3) If you think that we could stop here and make this our RandomX, as it's pretty good already,
      know that this minus the cache is a part of what Tor uses for it's client puzzles. All the
      techniques for burning through a CPUs ILP is replicated in Equi-X, among others.
*/
#slide(title: [(2.RX) SuperscalarHash], inset: 1em)[
  #set align(top)

  #grid(columns: (5fr, 4fr), gutter: 1em, gc[
    = *Algorithm.*

    #v(1em)

    ```
    cacheIndex = item number
    r0 = (item number + 1) * 6364136223846793005
    r1 = r0 ^ 9298411001130361340
    
    i = 0
    do {
        block = cache[cacheIndex % nr. 64 bytes in cache]
        SuperscalarHash[i](r0, r1, r2, r3, r4, r5, r6, r7)
        r0..7 ^= block[0..7]
        cacheIndex = r[longest dependency chain]
        i = i + 1
    } while(i < 8)

    item data = (r0|r1|r2|r3|r4|r5|r6|r7)
    ```

    #uncover((2, 3))[
      #l-m-hr()    
      #l-m-meta[(That's really all there is to the Dataset.)]
    ]
    #uncover(3)[

      https://github.com/tevador/equix #l-m-meta[(Tor)]
    ]
  ], gc[
      #set text(size: 0.8em)
      ```yasm
      getItem:
        ; r0 = (itemNumber + 1) * 6364136223846793005
        mov r8, rdi
        add r8, 1
        mov rax, 6364136223846793005
        imul r8, rax

        ; r1 = r0 ^ 9298411001130361340 ... and so on for r2-r7
        mov r9, -9148333072579190276   ;
        xor r9, r8                     ; r9 (r1) = r0 ^ constant
        mov r10, -6381431487974942650  ;
        xor r10, r8                    ; r10 (r2) = r0 ^ constant
        ; ...
        ; ...
        ;
        ; execute SuperscalarHash[i](r0, ..., r7)

        ; each invocation is unrolled in the generated code,
        ; no loop here.
        imul r12, r15             ; IMUL_R r4, r7
        imul r13, r14             ; IMUL_R r5, r6
        imul r10, r11             ; IMUL_R r2, r3
        lea r14, [r14 + r11*2]    ; IADD_RS r6, r3 (shift 1)
        xor r15, r9               ; IXOR_R r7, r1
        mov rax, -1727223807      ;
        xor r8, rax               ; IXOR_C r0, imm32
        sub r15, r14              ; ISUB_R r7, r6 (going down ↓)
        ; ...................
      ```
  ])
]

/*
- So, to recap:
*/
#slide-background(
  background: image("randomx architecture dataset.png", fit: "cover", width: 110%, height: 110%),
  inset: 1.2em
)[
  #set align(top)
  #set text(size: 0.8em)

  #grid(columns: (10fr, 9fr), gutter: 0em, gc[], gc[
    Pre-initialisation.

    - The key $K$ is passed to the SSH generator, which generates 8 hash functions.
    - $K$ is also used to fill 256 MiBs of static memory.

    #l-m-hr()
    Dataset-initialisation.

    - Each 64-byte Dataset item is generated by executing each of those 8 functions, and XORing data from the cache.
    - Cache $==>$ Dataset.
  ])
]
/*
- An important thing to remmeber here is that we can generate the 2 GiBs of the
  dataset upfront and store it straight in DRAM. Or, which is slower, generate
  each dataset item on the fly when we need it.
*/

/*
- (1) What we want to achieve with the dataset is simple. The goal is memory
      hardness, which is a property of functions that are hard to evaluate
      efficiently without a large amount of memory.

      This is pretty fitting for RandomX, as CPUs have access to memory controllers, so that means reading, writing and prefetching up to tens
      of gigabytes of DRAM.

      Let's consider two ASIC designs to beat the CPU's slow external DRAM.

- (4) An ASIC for fast mode mining at the time of RandomX's introduction
      would simply be not possible, as 2 GiBs of memory would be economically
      infeasible to store on-chip. You would lose out of the advantage of on
      chip memory, and would have to use external DRAM, then at that point
      there is no advantage to a CPU.
*/
#slide(title: [(2.RX) Memory-Hardness])[

  #uncoverb(2)[*Goal.* Sufficient memory-hardness.]
  #uncoverb(3)[
    #l-m-meta[(Let's consider two ASIC designs!)]
  ]

  #l-m-hr()

  #uncoverb(4)[
    - *(1)* 2 GiBs of on-chip low latency SRAM
      
      #uncoverb(6, l-m-meta[(An ASIC for fast mode mining is infeasible.)])
  ]
  #uncoverb(5)[
    #v(1em)
    $==>$ Try to make light mode mining viable?
    #v(1em)
  ]
]

/*
- (2) ... So, this ASIC will opt to only store the cache, and execute the
      8 superscalarhash instances. Is that much slower?

- (3) Because the superscalarhash generator, which is a CPU simulator, tries
      its hardest to maximise the dependency chain for all the registers
      across the instructions so an ASIC can't just evaluate the entire
      hash in parallel. Since each instruction depends on the previous one
      maximally, OoO execution and the superscalar nature of CPUs will be
      able to evaluate it efficiently. An ASIC would lose a lot of efficiency
      on the performance front.

- (4) Also, it uses an incredible amount of power. Equivalent to just using
      external DRAM like a regular CPU.
*/
#slide(title: [(2.RX) Memory-Hardness])[
  Let's try a competitive light mode mining ASIC?
  
  #uncoverb(2)[
    - *(2)* Light mode mining, 256 MiB of on-chip memory, 1-cycle latency for ops.
  ]

  #uncoverb(3)[
    #set text(size: 0.8em, l-m-meta-colour)

    #v(1em)

    The average SuperscalarHash function contains a total of 450 instructions, out of which 155 are 64-bit multiplications. On average, the longest dependency chain is 95 instructions long.
  
    \[...\]

    #uncoverb(4)[
      It will have to execute 155 \* 8 = 1240 64-bit multiplications per item, which will consume energy comparable to loading 64 bytes from DRAM.
    ]
  ]
  #v(1em)

  #uncoverb(2)[*Result.*] #uncoverb(5)[
    No advantage over CPU.
  ]
]

/*
- (1) So, given that we know that the Dataset takes advantage of the fact
      that CPUs are superscalar, and that Dataset initialisation is uniquely
      memory hard in the sense that creation of an ASIC that calculates the
      dataset ahead of time compared to calculating the items on demand, either
      has no advantage over a CPU.

- (2) Could we stop here? Consider an alteration of the dataset side of RandomX,
      with a new hash function that takes in a fixed key K and a large integer N,
      somehow hypothetically being an index into some dataset item.

      Assuming this is a good hash function: have we done enough?

- (3) The answer is not really, we do win memory hardness, but the fact that
      the superscalar hashes are superscalar isn't that useful. It's only to
      discourage the light mining ASIC design by burning huge amounts of energy,
      giving it no advantage over superscalar CPU designs.

      We only win memory hardness here.

      So, we need a whole other execution model, the RandomX VM, where as much
      of the CPU's capabilities are used.

- (9) Remember the goal here, we want to make the creation of an ASIC for RandomX
      as economically infeasible as possible, and which if an ASIC were to be
      created, it would resemble a CPU.

      Hence, every feature we include here that CPUs already have will
      increase the die area, the chip size, which will make it very expensive to
      manufacture a custom ASIC.
*/
#slide-background(
  background: image("randomx architecture dataset 1.png", fit: "cover", width: 110%, height: 110%),
  inset: 1em,
)[
  #set align(top)
  #set text(size: 0.9em)

  #grid(columns: (12fr, 10fr), gutter: 0em, gc[], gc[
    #uncoverb(2)[*Could we stop here?*]

    #uncoverb(3)[
      Not really.
    
      #l-m-meta[(Superscalar enables memory-hardness.)]

      #l-m-hr()
    ]

    #uncoverb(4)[
      #list[Superscalar instructions.]
    ]

    #uncoverb(5)[
      #list[Readable/writable memory.
        
        #l-m-meta[(L1, L2, L3 caches.)]
      ]
    ]


    #uncoverb(6)[
      #list[Instruction decoding.
      
        #l-m-meta[(μop cache)]
      ]
    ]
    
    #uncoverb(7)[
      #list[Floating point (IEE754), and (more) ALU.]
    ]

    #uncoverb(8)[
      #list[Branches/branch prediction.]
    ]

    #uncoverb(9)[
      #list[Native AES.]
    ]

    #uncoverb(10)[
      #l-m-hr()

      *Each increases die area for an ASIC!*
    ]
  ])
]

/*
- (1) Going back to the high level view, here is a recap.
      
      TODO
*/
#slide-background(
  background: image("randomx architecture simplified.png", fit: "cover", width: 120%, height: 120%),
)[]

/*
- (1) We have that they RandomX virtual machine is only concerned with the
      input hash bytes, not so much the key.

      On a high level there are four main sections of the VM, which are the
      scratchpad (which is the working memory of this imaginary CPU), the
      program buffer (which just holds the instructions), the register file,
      and the abstract virtual machine which describes the way to execute
      each program.

      You can follow the yellow lines as the flow of initialisation bytes,
      and the purple lines as the result flow, like the image for the dataset.

- (2) I will go through the general algorithm, and make note of some of the
      cryptographic primitives used.

- (3) An initial seed is calculated by hasing the input using Blake2b, then
      the scratchpad is entirely filled from random bytes using AesGenerator1R,
      which is a RandomX specific random bytes generator that uses one round
      of AES to mix up the state.

- (4) The program buffer is filled, which is basically all the state needed
      to program an instance of the RandomX virtual machine. 128 bytes are
      set aside to be loaded into the register file, and 2048 bytes is the
      actual program.

      This uses AesGenerator4R, which is the same as 1R, but uses 4 rounds
      of AES. The previous state of the 1R generator is fed into the 4R
      generator.

      An important thing to note is the choice of using AES here, most CPUs
      have a native instruction set for calculating AES rounds (AES-NI on
      Intel, same exists for Arm and Risc-V), which we mentioned before.

      The AES generators are sufficient in an avalanche of the input bits,
      but, the generator is reversible and doesn't make for a good hash
      function, which is why it is always initialised with a non-reversible
      hash function which is Blake2b with the seed there.

      The VM is executed along with all the instructions, filling up the
      scratchpad and register files with entropy, and reading from the
      dataset. I'll explain the instruction set later on.

      Last, the register file is hashed with Blake2b and copied to the
      AesGenerator4R* state which we're keeping around to generate
      an entirely new program, going around steps 3-5 again.

      The important thing to note here, is that we execute 8 randomly
      generated programs, where the output of one program is used to
      generate the program after. The reasons for this will come in
      the next slide.

- (5) So after we executed the 8 programs, we have a scratchpad which
      is just filled with entropy, so we hash it using the 1R generator
      (which is fast), and the final result is calculated as the hash of
      the scratchpad with a portion of the register file with Blake2b.
*/
#slide-background(
  background: move(dy: 8pt, image("randomx architecture vm.png", fit: "cover", width: 100%, height: 100%)),
  inset: 1.2em
)[
  #set align(top)
  #set text(size: 0.8em)

  #grid(columns: (17fr, 24fr), gutter: 0em, gc[
    #uncoverb(2)[
      *Algorithm.*
    ]

    #uncoverb(3)[
      1. Initial seed S is calculated. #l-m-meta[(Blake2b)]
      2. Scratchpad is filled. #l-m-meta[(AesGenerator1R=S)]
    ]

    #uncoverb(4)[
      #l-m-hr()

      3. Program Buffer filled. #l-m-meta[(AesGenerator4R\*)]

        #l-m-meta[(VM is programmed from contents)]
      
      4. *The VM is executed.*
      5. Register file is hashed and copied to AesGenerator4R\* state.
      6. Steps 3-5 are performed *8* times.

        #l-m-meta[(chained VM execution)]
    ]

    #uncoverb(5)[
      #l-m-hr()

      7. Scratchpad fingerprint is calculated. #l-m-meta[(AesGenerator1R)]
      
      8. Final result R is the hash of scratchpad fingerprint + register file. #l-m-meta[(Blake2b)]
    ]
  ], gc[])
]

/*
- (1) There is a very good reason RandomX opts to execute 8 different
      programs in a chain.

- (2) Remember that mining is simply just finding an integer called
      the nonce that when you concat the block data, the transactions,
      with the nonce it hashes to a value that is acceptible, within
      a certain difficulty.

- (3) Given this, since the nonce can be any number, why not just
      optimise for the easy programs, and skip the hard ones?

- (4) Well, if you had to execute multiple programs in a chain, aborting
      on an unfavourable program would be pretty expensive because you'd
      have to throw away all your previous work.

      RandomX doing 8 chained programs in a row means that you're forced
      to commit to executing them all, otherwise you'd be much slower than
      just biting the bullet.
*/
#slide-background(
  background: move(dy: 25%, image("randomx easy program problem.png", fit: "contain", width: 100%, height: 100%)),
  title: [(2.RX) Easy program problem],
)[
  #set align(top)

  #gc[
    #uncoverb(2)[
      - Mining is evaluating HASH(block $⊕$ nonce), where nonce = 0, 1, 2, ...

        #l-m-meta[(until a successful hash is found.)]
    ]

    #uncoverb(3)[#list[Why not just nonce++ when an unfavorable #l-m-meta[(hard)] program is found?]]
    
    #uncoverb(4)[
      #l-m-hr()

      *Reason.* Chaining programs forces you to commit, or take a #l-m-meta[(time)] penalty.
    ]
  ]
]

/*
- Scratchpad
  (writes, reads)
  (L1, L2, L3)
- VM instructions
  (why floats too!)
- registers
*/
